### ISSUE TITLE
Another false positive for format string with numbered arguments

### ISSUE THREAD

**Issue by smee** [borkdude/clj-kondo#1000]
**version**

v2020.07.29

**platform**

Native version for linux, Ubuntu

**problem**

The warning for missing arguments seems to show a false positive, but only with multi-line format strings and numbered arguments.

**repro**

>$ cat format.clj
(format "%1$s %2$s
"
        "arg1" "arg2")

> $ clj-kondo --version
clj-kondo v2020.07.29

> $ clj-kondo --lint format.clj
format.clj:1:9: error: Format string expects 1 arguments instead of 2.
linting took 16ms, errors: 1, warnings: 0

![image](https://user-images.githubusercontent.com/36397/92452268-1cf32b00-f1be-11ea-969e-95ace4b39c6c.png)

**config**

empty config

**expected behavior**

There should not be any warning.

**Comment by borkdude** [comment]
@smee Thanks. I think this has been fixed in https://github.com/borkdude/clj-kondo/issues/949 (which got closed prematurely, since I only close issues after they've been released). A release is coming soon. Alternatively you can grab a binary from one of the latest CircleCI or Github builds.
