### ISSUE TITLE
Config setting to ignore :as bindings in unused binding linter

### ISSUE THREAD

**Issue by expez** [borkdude/clj-kondo#1016]
The current unused binding linter treats the following destructuring in a uniform way:

```(defn [{:keys [address id] :as user}])```.  If `id` goes unused I like to be to told, because maybe I forgot to do something with it, but I don't want it to tell me that `user` is unused. 

 `:as user` is a lightweight way (as opposed to say using specs) to let someone know that the full map contains the data usually associated with a `user` and isn't a `business` or a `server` even though those too might have an `address` and an `id`.

The current config looks like this:

```
:unused-binding {:level :warning
                 :exclude-destructured-keys-in-fn-args false}
```

Perhaps it could be extended with something like:

```
:unused-binding {:level :warning
                 :exclude-destructured-keys-in-fn-args false
                 :exclude-destructured-as false}
```

**Comment by borkdude** [comment]
I usually solve this with `:as _user` which I think is sufficient for giving the whole a name.

**Comment by expez** [comment]
Thanks for the suggestion, but I don't want to refactor a rather large production app to conform to the worldview of the tooling du jour. 

The use of `_user` also opens up a more subjective discussion about aesthetics.

We recently switched from `eastwood` to `clj-kondo` and the speedup in build times on our CI server has been a huge boon.  I can't see a way back, but there's already some work ahead to teach clj-condo about our code base to re-enable a few linters.

**Comment by borkdude** [comment]
@expez I think this touches on a different underlying problem: starting with an existing codebase, ignoring existing warnings.

There are a couple of ways to deal with this:

1) Spit out existing warnings to a file and diff with this file on successive lints in CI. You could also use EDN output and use a script (possibly babashka for quick startup, or just normal Clojure) to diff programmatically. 
2) Use a different or additional config for CI. See https://github.com/borkdude/clj-kondo/blob/master/doc/config.md and https://github.com/borkdude/clj-kondo/blob/master/doc/ci-integration.md.
Reviewdog is one of the tools that can do this diffing as well: https://github.com/reviewdog/reviewdog but I've never used it.

**Comment by borkdude** [comment]
As for the option: a PR is welcome.

**Comment by borkdude** [comment]
I was going to suggest another option, but it didn't work as expected:

```
(let [{:keys []
       :as #_:clj-kondo/ignore m}
      {}]
  )
``` 

I'm going to make an issue for that.

**Comment by expez** [comment]
We've gone with option 2).  A few linters are disabled on the CI server, but we have all of them enabled locally (and with editor integration).

I'm now working toward getting all the linters we care about enabled on the CI server, but wasn't sure how to solve this one.

> As for the option: a PR is welcome.

Good to know. I'll try to find time for that. 

Thanks for your help!  :)

**Comment by expez** [comment]
Thanks for indulging the feature request @borkdude, and thank you very much for your implementation @dharrigan! 🙏

**Comment by dharrigan** [comment]
@expez you're most welcome :)
