### ISSUE TITLE
Support requires in top-level dos

### ISSUE THREAD

**Issue by sogaiu** [borkdude/clj-kondo#1018]
**Is your feature request related to a problem? Please describe.**
Currently it doesn't appear possible to inform clj-kondo about the introduction of multiple namespaces / aliases via the hooks api.  Related https://github.com/borkdude/clj-kondo/issues/1019

**Describe the solution you'd like**
Support for processing `require` in top-level `do` forms is one of two things which if implemented would make it possible to teach clj-kondo via the hooks api, about the introduction of multiple namespaces / aliases via a single form.

**Describe alternatives you've considered**
Having the hooks api support returning multiple nodes.  I have no idea how much work this would be though.

**Additional context**
There is a construct in libpython-clj called `import-python` which when evaluated leads to the introduction of 7 or so namespaces / aliases.

It seems that without support for requires in top-level dos, even using the current hooks api, clj-kondo cannot be appropriately instructed.

**Comment by sogaiu** [comment]
I tried out master and so far it looks like both #1018 and #1019 are working :+1:

One thing I failed to request is aliasing via :as -- i haven't gotten that to work.  Is that supposed to?

I'm turning `(import-python)` into basically:

```
(do
  (require (quote [builtins.list :as python.list]))
  (require (quote [builtins.dict :as python.dict]))
  ,,,
  )
```
the `builtin.list`, `builtin.dict` appear to be recognized but not the `python.list`, `python.dict`, etc.

For the Clojure source:
```
(ns libpython-clj.fun
  (:require [libpython-clj.require :refer [import-python]]))

(import-python)

(builtins.list/fun)

(python.list/fun)
```
when I run `clj-kondo --lint src/libpython-clj/fun.clj` I get:
```
src/libpython_clj/fun.clj:8:2: warning: Unresolved namespace python.list. Are you missing a require?
linting took 14ms, errors: 0, warnings: 1
```

My interpretation is that `builtins.list` is being properly recognized, but not `python.list`.

The (reduced) hooks code is basically:
```
(defn import-python
  [{:keys [:node]}]
  (let [new-node (with-meta (api/list-node
                             [(api/token-node 'do)
                              (api/list-node
                               [(api/token-node 'require)
                                (api/list-node
                                 [(api/token-node 'quote)
                                  (api/vector-node
                                   [(api/token-node 'builtins.list)
                                    (api/token-node :as)
                                    (api/token-node 'python.list)])])])
                              (api/list-node
                               [(api/token-node 'require)
                                (api/list-node
                                 [(api/token-node 'quote)
                                  (api/vector-node
                                   [(api/token-node 'builtins.dict)
                                    (api/token-node :as)
                                    (api/token-node 'python.dict)])])])])
                   (meta node))]
    {:node new-node}))
```

**Comment by borkdude** [comment]
@sogaiu FWIW, this code lints correctly:

``` clojure
(do
  (require (quote [builtins.list :as python.list :refer [bar]]))
  (require (quote [builtins.dict :as python.dict])) ;; required but never used
  ,,,
  )

(python.list/foo)
(bar)
#_(python.dict/foo)
```

Maybe an issue with the hook.

**Comment by borkdude** [comment]
I can repro this locally now.

**Comment by borkdude** [comment]
@sogaiu Added `keyword-node` to the hooks API now. Please use that one to produce keywords, then it should work.

**Comment by sogaiu** [comment]
That seems to have done the trick :+1:
