### ISSUE TITLE
Type warning for contains? on seq

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#1021]
``` 
(contains? (map :name tags) "foo")
``` 
should give a type warning.

**Comment by yuhan0** [comment]
The commit which closed this does not seem right (https://github.com/borkdude/clj-kondo/commit/d3b71fcf2596defccd0333fafd5378dac4b71846)

While using `contains?` on a vector (associative) is valid, it's quite likely to be an error:
```clj
(contains? [:a :b] :a)
;; => false
(contains? [:a :b] 0)
;; => true
```

`contains?` also does not work on strings:
```clj
(contains? "abc" \a)
;; => Execution error (IllegalArgumentException) at repro/eval135854 (REPL:83).
;;    contains? not supported on type: java.lang.String
```



I believe a better type signature for it would be
```clj
{:arities {2 {:args [#{:map :set} :any] 
              :ret boolean}}}
```

If that sounds alright I can open a PR.

**Comment by borkdude** [comment]
Contains is supported on vectors and strings, but the key should be numeric in that case. Remember that contains checks for key values, and strings are considered arrays keyed by their index. As such, I don't see a reason to change the existing type.

https://github.com/clojure/clojure/blob/f47c139e20970ee0852166f48ee2a4626632b86e/src/jvm/clojure/lang/RT.java#L830-L853

**Comment by yuhan0** [comment]
Thanks for the clarification, I didn't realise it worked on strings depending on the 2nd arg, and I suppose the current type system can't express something like `[#{:string :vector} :int] OR [#{:map :set} :any]`.

Using `contains?` on a string or array still seems to me like a likely bug or at the least an unidiomatic way of checking the array bounds, but that's a separate issue.
