### ISSUE TITLE
Return count of files evaluated

### ISSUE THREAD

**Issue by pepijn** [borkdude/clj-kondo#1046]
**Is your feature request related to a problem? Please describe.**
I would like to make sure kondo evaluated at least one file. In a call like `(clj-kondo.core/run! {:lint [lint-path]})` the `lint-path` could be set up incorrectly, pointing to an existing directory without source files. If the directory exists there is no way to distinguish a successful run (evaluating at least 1 source code file) from a run on a directory without source files.

**Describe the solution you'd like**
Add a value to the `clj-kondo.core/run!` result map (in `:summary`?) that contains the number of files evaluated. Similar to kaocha's `:kaocha.result/count` (https://cljdoc.org/d/lambdaisland/kaocha/0.0-359/doc/8-extending#testable).

**Describe alternatives you've considered**
A poor heuristic for finding whether it actually evaluated source code is by judging the `(-> :summary :duration)` value.

**Additional context**
I would like to do the PR myself.

**Comment by borkdude** [comment]
I think we could add a `:files` key to the summary. PR welcome.
