### ISSUE TITLE
Unable to resolve filesystem provider with relative file path

### ISSUE THREAD

**Issue by nakiya** [borkdude/clj-kondo#1050]
**version**

clj-kondo-2020.10.10
(I'm not using directly, but bundled with Calva v2.0.129)

**editor**

VSCode Calva

**problem**

Not sure if this is related to clj-kondo, but I see that the path in the error includes it.

I have calva installed in VSCode.

I am Just trying to do a REPL jack-in using ctrl+alt+c ctrl+alt+j. (This has worked many times in the past.)

Then I get this error: Unable to resolve filesystem provider with relative file path 'd:\work\projects\formula/.calva/output-window/.clj-kondo' (d:\work\projects\formula is my project folder, I don't see a .calva folder created there though.)

I tried restarting VSCode/machine, moving project location, creating new fresh project, etc and nothing works.

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**repro**

I don't know how to reproduce

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

**Comment by borkdude** [comment]
I don't think this is related to clj-kondo but maybe @PEZ knows more.

**Comment by borkdude** [comment]
Please post this issue in the Calva repo as I don't think this is related to clj-kondo itself.
