### ISSUE TITLE
Default configuration suggestion: change default :single-operand-comparison level to error

### ISSUE THREAD

**Issue by saitouena** [borkdude/clj-kondo#1065]
**Is your feature request related to a problem? Please describe.**
In my experience, single-operand-comparison like `(= x)` has never been my intension.
For example, I sometimes write a nonsense test like `(is (= some-big-expression-here) (f x))`.

**Describe the solution you'd like**
https://github.com/borkdude/clj-kondo/blob/9aaee5023a5da511cedd3b77bd64a35a51636416/src/clj_kondo/impl/config.clj#L85
I think that linting single-operand-comparison as an error is default better configuration because it is always meaningless.

Any ideas?

**Comment by borkdude** [comment]
People can tweak this level in their own config, so I don't think a change is needed. The code will still compile, hence it is a warning.
