### ISSUE TITLE
Document enhancement: add a comprehensive list of linters

### ISSUE THREAD

**Issue by saitouena** [borkdude/clj-kondo#1067]
**Is your feature request related to a problem? Please describe.**
I cannot find a document that has a list of all linter.
It would be helpful to override the default setting of clj-kondo and be also helpful to find a new linter.

**Describe the solution you'd like**
What about adding a section of all linter description to `doc/config.md` based on [config.clj](https://github.com/borkdude/clj-kondo/blob/9aaee5023a5da511cedd3b77bd64a35a51636416/src/clj_kondo/impl/config.clj#L13)?

The list would be huge so it might be better to make a new `doc/linters.md`.

**Comment by borkdude** [comment]
Yep, great thoughts. This is also requested in #936 which is about to get picked up, so I'm closing this as a duplicate.
