### ISSUE TITLE
Release v2020.12.09 missing tag

### ISSUE THREAD

**Issue by cez1** [borkdude/clj-kondo#1096]
There is no tag for release v2020.12.09, causing the release not found from Releases. The installation script is broken, because it can't find the release related zip-file from https://github.com/borkdude/clj-kondo/releases/download/v2020.12.09/

**Comment by borkdude** [comment]
Sorry about that. I was in the processing of releasing, but aborted it due to a new issue which I wanted to get in. The changes to the install script have been reverted now.

**Comment by borkdude** [comment]
See #1095.
