### ISSUE TITLE
Windows: scan jar entries from META-INF/MANIFEST.MF created by lein-classpath-jar 

### ISSUE THREAD

**Issue by FongHou** [borkdude/clj-kondo#1107]
**Is your feature request related to a problem? Please describe.**

This is related to @ericdallo's work on Calva. He's been trying to integrate clojure-lsp along with clj-kondo as linter and jar metadata scanner. Some clojure-lsp features seem not working without full metadata from dependent jars on classpath.

**Describe the solution you'd like**

I'm not sure whether clj-kondo currently scan jar entries from META-INF/MANIFEST.MF created by lein-classpath-jar or not. clj-kondo seems only scan entries in CLASSPATH environ variable.

**Describe alternatives you've considered**

I just want to raise this as a question first. This issue doesn't exist on linux/macos.

**Additional context**

https://github.com/clojure-lsp/clojure-lsp/issues/223

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

**Comment by ericdallo** [comment]
Just to clarify, I'm just a clojure-lsp maintainer who is helping @PEZ and @bpringe make Calva use clojure-lsp 😅

**Comment by borkdude** [comment]
@FongHou @ericdallo Clj-kondo never scans anything beyond what you will give it via the `--lint` argument. When you give it a classpath with .jar files in it, it will lint all the .clj/.cljs/.cljc files in it, but not in a particular order.

**Comment by ericdallo** [comment]
So the issue may be that clojure-lsp should make clj-kondo scan jars for that path for window too, right?

**Comment by borkdude** [comment]
If you rely on clj-kondo having analysed certain libraries, then you should make clj-kondo lint them manually: it doesn't scan anything on its own.
