### ISSUE TITLE
False positive using funcool/cats

### ISSUE THREAD

**Issue by mynomoto** [borkdude/clj-kondo#114]
There are some threading macros on `cats.core`: `->=` `->>=` and `as->=` that are causing wrong number of args on a project that I have.

Also I would like to thank you for this project. It's very helpful!

**Comment by borkdude** [comment]
Thanks! 

Is this project public so I can try it myself? I might turn off linting arities in all unknown macros, I'm not sure yet. If a macro behaves kind of like `->`, I could expand it the same way. So I'd like to try this on a real example.

**Comment by mynomoto** [comment]
Those behave like `->`, `->>` and `as->`. That project is not public but I will set up a public one with using those macros.

**Comment by borkdude** [comment]
@mynomoto A gist is fine too with some typical examples.

**Comment by mynomoto** [comment]
There you go: https://gist.github.com/mynomoto/084c640ef90c333861a1ab71e9688b36

**Comment by borkdude** [comment]
@mynomoto Should be fixed in https://1748-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.04.22-alpha-SNAPSHOT-linux-amd64.tar.gz. Can you test and report back?

**Comment by mynomoto** [comment]
This is great! I run on my project and it worked perfectly. No more wrong args warnings! Thank you very much!
