### ISSUE TITLE
Warning about unused imports

### ISSUE THREAD

**Issue by marcomorain** [borkdude/clj-kondo#162]
@marcomorain

One suggestion `/Users/marc/dev/circleci/circle/test/circle/bitbucket/test_client.clj:4:14: warning: unused namespace cheshire.core`

On first reading, this made my think that a namespace was unused - in fact it’s the import that’s not used. Maybe this would be more clear:

> warning: required namespace is unused

@pez
> TSLint would phrase it something like _namespace cheshire.core is required, but never used_.

**Comment by marcomorain** [comment]
https://clojurians.slack.com/archives/CHY97NXE2/p1557833610022900

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/c652b1b5be72884d483e93dc30a100d60450f630
