### ISSUE TITLE
Config link points to a 404 page

### ISSUE THREAD

**Issue by mynomoto** [borkdude/clj-kondo#165]
When running `clj-kondo` without arguments there is a link on the `--config` section that points to https://github.com/borkdude/clj-kondo/blob/config/doc/config.md

**Comment by borkdude** [comment]
Thank you. The link should be https://github.com/borkdude/clj-kondo/blob/master/doc/config.md. I'll update it.

**Comment by borkdude** [comment]
Fixed with 08e0b77cbdc75f8d480bf3d382674a4cd1888e87
