### ISSUE TITLE
return analysis results

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#234]
find usages (disguised as a linter):

```
$ cat config.edn
{:linters
 {:find {:references
         {:vars [foo/bar]
          :keywords [:foo/bar]
          :namespaces [foo]}
         :defs [foo/bar]}}}

clj-kondo --lint src --config config.edn
src/foo/baz.clj:13:2: info: namespace foo is used
src/foo/baz.clj:13:2: info: var foo/bar is used
src/foo/baz.clj:16:1: info: keyword :foo/bar is used
```

There might be other types of linters just for extracting information out of the analyzed code, e.g. public var arities. 

This probably needs a little bit of hammock time.

**Comment by neotyk** [comment]
It would be super useful if this way we could find usages of keywords too.
Especially namespaced keywords, and a corner case where ns of the keyword is not requires but rather spelled out in the keyword itself.

**Comment by borkdude** [comment]
Updated the example to include keywords and namespaces.

**Comment by lread** [comment]
Hi @borkdude! As we chatted about on Slack, I'm interested in checking for API breakages. Unit tests can cover behavioral breakages, but a check for an unintended change in function signatures for a library's public API would be nice. One might argue that API breakages are deliberate and such a tool would be unnecessary, but I'm thinking of cases where a contributor not intimately familiar with a library or its philosophy might make an unintended breakage.

My current specific use case is merging rewrite-cljs and rewrite-clj into a cljc project. I'd like a quick way to check that I have not broken existing public APIs.  So I'd be comparing current rewrite-cljs against my cljc project and also current rewrite-clj against my cljc project.

A complexity is that rewrite-clj uses a version of potemkin import-vars which I have carried over to the cljc merge.

Although rewrite-clj doesn't currently spec functions, I suppose a general solution would also consider specs on public API functions.

Neglecting spec, and before you brought clj-kondo to my attention as a potential candidate, I was thinking of basing a tool on the work done in [cljdoc's adaptation to codox](https://github.com/cljdoc/codox/tree/cljs-proper) which currently handles import-vars for clj and will soon do so as well for cljs.

**Comment by sogaiu** [comment]
> find usages (disguised as a linter):

How about find definitions?

**Comment by borkdude** [comment]
@neotyk @lread @sogaiu I've chosen not to implement this as a linter, but to expose analysis results as data. Other tools/scripts can pick up on this data. In the end this is more flexible. Examples of how this data could be used:
https://github.com/borkdude/clj-kondo/tree/dump-analysis/tools
Note that this is work in progress in a branch. If the branch is deleted, I'll update the link here.

**Comment by borkdude** [comment]
Continuing in #373.
