### ISSUE TITLE
support potemkin's import-vars

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#237]

**Comment by borkdude** [comment]
@lread if you want to test it, this is the most recent Mac version: https://5216-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.08.01-alpha-SNAPSHOT-macos-amd64.zip
The branch I have developed this in is https://github.com/borkdude/clj-kondo/tree/import-vars.
I'm pretty much ready to merge this.

**Comment by lread** [comment]
Thanks! I will give it a go sometime this weekend on rewrite-cljs-playground!

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/e754f6baf87ee739165e1f932ddb06ffda1bf826
