### ISSUE TITLE
Configuration file for all rules

### ISSUE THREAD

**Issue by suni-masuno** [borkdude/clj-kondo#239]
**Feature Description**
Create support for a `kondo-config.clj` or similar file that will allow direct control over what rules are active, and potentially configure rules where that would be useful.

**Context**
One of two requests that boil down to "Do the things that made me like eslint".

In practice I found one of my primary use cases for code quality static analysis is allowing teams to discuss and agree upon rules. 

Allowing each rule to be controlled, and in some cases even configured, has allowed teams I've worked on to achieve code quality even higher than the rules themselves would have driven. This is because it allowed the entire team to discuss, understand, and agree upon the rule before obeying it.

**Comment by borkdude** [comment]
@suni-masuno Have you already looked at https://github.com/borkdude/clj-kondo/blob/master/doc/config.md?

**Comment by suni-masuno** [comment]
Honest answer, was making sure I wrote this down before our slack conversation left my brain, doing my real detailed reading after.

**Comment by borkdude** [comment]
The clj-kondo config already supports this, see the docs. I suggest you try out clj-kondo for a while and if anything is missing, feel free to open a new ticket.
