### ISSUE TITLE
Plugin oriented design.

### ISSUE THREAD

**Issue by suni-masuno** [borkdude/clj-kondo#240]
**Feature Description**
A plugin oriented design, allowing for both rules and configurations to be driven by outside plugins.

**Context**
One of two requests that boil down to "Do the things that made me like eslint".

One of the primary driving values I experienced with linters was how much they would help with large and challenging new libraries when those libraries exposed eslint plugins/recommends.

I've also found large groups, IE corp departments, found great utility in the ability to publish their chosen internal style as a recommends and/or plugin.

Perhaps most importantly though I've found members of the community come up with surprising and surprisingly brilliant rules that no dev team, no matter how clever, could have hoped to come up with ahead of time.

**Comment by borkdude** [comment]
This is probably not going to work for a statically compiled tool like clj-kondo, although the idea is nice.
