### ISSUE TITLE
Warn about doc-strings following arg-vector

### ISSUE THREAD

**Issue by didibus** [borkdude/clj-kondo#243]
An issue I see a lot is people write code like this:

```
(defn add [a b]
  "Adds a and b together."
  (+ a b))
```
Where they put the doc-string after the arg-vector by mistake. It would be nice to have a warn for it.

**Comment by borkdude** [comment]
@didibus This can be tested using a binary or via clj:

```
clj -Sdeps '{:deps {clj-kondo {:git/url "https://github.com/borkdude/clj-kondo" :sha "d8fc63f549e20086ed1b7c502eae694fb0ddaae9"}}}' -A:clj-kondo --lint foo.clj
```

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/1f24981d38b85f2d823f8f57bb252e0705bc1ebd
