### ISSUE TITLE
wrong number of args error could mention the right number

### ISSUE THREAD

**Issue by johanatan** [borkdude/clj-kondo#248]
**version**

Latest.

**platform**

Mac.

**problem**

The following error would be more helpful if it mentioned also the correct number of arguments:

```
error: wrong number of args (2) passed to XXX
```

**repro**

Create a function and pass it the wrong number of args. Run clj-kondo on it.

**expected behavior**

Better message.

**actual behavior**

Worse message.

**Comment by borkdude** [comment]
A function can have multiple arities, so the message could be something like:

```
error: wrong number of args (2) passed to XXX, expected 1,3,4 or 5+
```
Does that make sense?

**Comment by johanatan** [comment]
Yep. 👍🏻

**Comment by borkdude** [comment]
TODO: 
- [ ] fix 79 failing tests for which the message now has changed

**Comment by borkdude** [comment]
Preview:

<img width="349" alt="incorrect-arity-expected" src="https://user-images.githubusercontent.com/284934/60302498-4bc40f00-9934-11e9-9531-5d4c25e5034b.png">

TODO: 
- [ ] fix 79 failing tests for which the message now has changed

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/a6585f47a5efc1b3ce418480971f9dc3da0f956a
