### ISSUE TITLE
Warn about constantly true expression `(= foo)`

### ISSUE THREAD

**Issue by tatut** [borkdude/clj-kondo#260]
1-arity use of `=` that is useful for apply, but most likely a mistake if used like `(= foo)` because it is constantly true.

**Comment by borkdude** [comment]
If you like early access to this, this can be implemented as a custom linter by checking if the arity for the var usage `clojure.core/=` was 0 or 1.
See https://github.com/borkdude/clj-kondo/tree/master/analysis.

**Comment by tatut** [comment]
Same goes for normal comparisons, like `(< 1)`. Always true and most likely a bug.

**Comment by EwaTrzemzalska** [comment]
I'd love to try to tackle this one! These are my first steps in the world of Clojure, and programming in general, so I'd appreciate some tips for how to implement this.

**Comment by borkdude** [comment]
@EwaTrzemzalska Here are some instructions to get a REPL, etc for clj-kondo:

https://github.com/borkdude/clj-kondo/blob/master/doc/dev.md

Most of the analysis happens in `src/clj_kondo/impl/analyzer.clj`. I think we will have to add a case there for `clojure.core/=` and then check the amount of children nodes. There are several examples of this, e.g.:

```
$ clj -A:clj-kondo --lint - <<< "(defn foo [x] (if-let [x 1] x x x))"
<stdin>:1:15: error: if-let body requires one or two forms
linting took 73ms, errors: 1, warnings: 0
``` 

You can also start by adding a test in `test/clj_kondo/main_test.clj` and then try to get the test working.

**Comment by borkdude** [comment]
Is it a co-incidence that @EwaTrzemzalska asked about this issue and shortly after @abogoyavlensky makes a commit regarding this issue? Are you two working together somehow?

**Comment by abogoyavlensky** [comment]
@borkdude No, seems that it is happened accidentally.
