### ISSUE TITLE
support linting .edn files

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#270]
cc @mynomoto

**Comment by borkdude** [comment]
@mynomoto
This version should be able to lint .edn files: https://3874-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.06.17-alpha-SNAPSHOT-linux-amd64.zip

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/fe4272fb78be453b5c35061813a8c0e68e374eed

**Comment by mynomoto** [comment]
This worked, no false positives anymore on edn files. Thanks!
