### ISSUE TITLE
investigate building windows version via travis or appveyor

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#274]
Information to build on Windows: https://github.com/borkdude/clj-kondo/blob/master/doc/build.md#windows

**Comment by borkdude** [comment]
@lispyclouds has offered looking into this, thanks!

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/0c34418785c047dcb77c011ae22434a84d2612bb

**Comment by sogaiu** [comment]
@lispyclouds @borkdude That's great!
