### ISSUE TITLE
windows: consider chocolatey instead of scoop

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#283]
It seems chocolatey supports dependencies whereas scoop is just an installer without package management. With a dependency on https://chocolatey.org/packages/vcredist2010 we might be able to run clj-kondo out of the box on a bare Windows 10 system.

**Comment by sogaiu** [comment]
Based on the response from the Graal folks here:

https://github.com/oracle/graal/issues/1407#issuecomment-504912188

May be it makes sense to try this?
