### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by slifin** [borkdude/clj-kondo#303]
In Clojure it's possible to type hint your returns and arguments, in the Clojure community do we have a tool that can check your optional types at editor time?

**Comment by borkdude** [comment]
Related issue: https://github.com/borkdude/clj-kondo/issues/23

**Comment by borkdude** [comment]
Note that joker already supports this: 
![Screenshot 2019-06-28 13 12 55](https://user-images.githubusercontent.com/284934/60338511-751d8300-99a6-11e9-930a-3fdf8ef97f8b.png)

It can only do this when calling with literals expressions, so it's pretty limited, but useful. I plan to implement the same in clj-kondo in the future.

You can turn on both clj-kondo and joker in e.g. Emacs, as follows: 
https://github.com/borkdude/flycheck-clj-kondo#multiple-linters

**Comment by slifin** [comment]
Oh that's cool, I guess in cursive I can use the file watcher plugin to run joker too?

**Comment by borkdude** [comment]
I think so!

**Comment by borkdude** [comment]
This is now implemented (see #445).
