### ISSUE TITLE
Support warning on deprecated

### ISSUE THREAD

**Issue by lread** [borkdude/clj-kondo#338]
**Is your feature request related to a problem? Please describe.**
I'd like to be warned when I am using deprecated functions. I would not like to be warned when my deprecated functions:
1. call my deprecated functions
2. are called from my tests that exercise those functions

**Describe the solution you'd like**
Warning on deprecated calls seems easy.  A new `:deprecated` linter would seem to be the way to go. 

Handling the exclusions requires a bit more thought. As a detail: I think I still want to be warned when I am calling from one of my deprecated function to someone else's deprecated function. 

**Some spit-balling**
Maybe something like?:
```clojure
{:linters
 {:deprecated
  {:exclude [{:from ^:deprecated <ns/fn regex> :to <ns/fn regex>}]}}}
```

How might this work for me?
```clojure
{:linters
 {:deprecated
  {:exclude
   [;; maybe this for my src
    {:from ^:deprecated rewrite-clj.* :to rewrite-clj.*}
    ;; and maybe these for my tests
    {:from rewrite-clj.regresion-test :to rewrite-clj.*}
    {:from rewrite-clj.examples.cljx-test :to rewrite-clj.*}
    {:from rewrite-clj.whitepace-test :to rewrite-clj.*}]}}}
```

If I step back and think of other use cases, I can imagine someone wanting to exclude deprecated warnings:
1. to another library  
`:exclude [{:to other-library-namespace.*}]`
2. for calls to a specific function  
`:exclude [{:to other.library.namespace/specific-function}]`
3. for calls from a specific test to own library 
`:exclude [{:from my-library.test-name-space/my-test :to my-library.*}]`

Anyway, that's just a first thought and I'm sure could be improved/generalized/simplified/borkedudefied.

**Describe alternatives you've considered**
I am currently taking advantage of the `:fn-deprecated` warning the cljs compiler emits. I have a custom [warning-handler](https://cljs.github.io/api/compiler-options/warning-handlers) to suppress the deprecation warnings I am not interested in. My current solution is more brittle than I'd like.

**Additional context**
A deprecated function is one that is marked as such with `:deprecated` metadata.  
1. [example from clojure source with metadata after fn name](https://github.com/clojure/clojure/blob/ee3553362de9bc3bfd18d4b0b3381e3483c2a34c/src/clj/clojure/core.clj#L5152)  
```clojure
(defn add-classpath
  "DEPRECATED 
  Adds the url (String or URL object) to the classpath per
  URLClassLoader.addURL"
  {:added "1.0"
   :deprecated "1.1"}
  [url]
  (println "WARNING: add-classpath is deprecated")
  (clojure.lang.RT/addURL url))
```
2. [example from rewrite-clj source with metadata before fn name](https://github.com/xsc/rewrite-clj/blob/e69d6404268b90bcc2b7f2c8119a80aeee20186a/src/rewrite_clj/zip.clj#L111)  
```clojure
(defn ^{:deprecated "0.4.0"} ->string
  "DEPRECATED. Use `string` instead."
  [zloc]
(string zloc))
```

**To consider**
1. In addition to `:fn-deprecated` warning, the cljs compiler also supports `:protocol-deprecated`. I don't know if clj-kondo would like to make such a distinction as well.
2. macros?

**Comment by borkdude** [comment]
TODO:
- [x] report when using a deprecated function
- [ ] report when using a deprecated var
- [ ] config

**Comment by borkdude** [comment]
@lread The first item in the comment above has been implemented with: https://4468-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.07.06-alpha-SNAPSHOT-macos-amd64.zip

**Comment by lread** [comment]
Very cool!  Just tried it!
```bash
$ clj-kondo --lint src test
src/rewrite_clj/zip/base.cljc:65:23: warning: #'rewrite-clj.node/value is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:148:20: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:153:32: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:156:32: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:161:27: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:164:26: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:166:27: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:169:26: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:231:48: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:238:16: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:238:37: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:239:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:240:32: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:246:16: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:246:37: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:247:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:248:32: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:255:16: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:255:37: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:256:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:257:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:258:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:263:16: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:263:37: warning: #'rewrite-clj.zip/->root-string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:264:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:265:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/regression_test.cljc:266:20: warning: #'rewrite-clj.zip/->string is deprecated since 0.4.0
test/rewrite_clj/zip/whitespace_test.cljc:40:49: warning: #'rewrite-clj.zip.whitespace/prepend-newline is deprecated since 0.5.0
test/rewrite_clj/zip/whitespace_test.cljc:42:49: warning: #'rewrite-clj.zip.whitespace/append-newline is deprecated since 0.5.0
linting took 601ms, errors: 0, warnings: 29
```

**Comment by borkdude** [comment]
@lread I borkdudefied the config to the following:

```
{:linters {:deprecated-var
                      {:exclude {foo.foo/deprecated-fn
                                 [foo.bar "bar\\.*"]}}}}
```

I think this covers the common usecase of suppressing deprecated warnings of specific functions in namespaces (by literal symbol or regex). I think this is sufficient, since the amount of deprecated functions will probably not be so big that these should also handled with regexes?

You can test this config with https://4472-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.07.06-alpha-SNAPSHOT-macos-amd64.zip.

**Comment by lread** [comment]
Hey thanks @borkdude! That is very close to meeting my ideal.  Here's what I've successfully tried on my rewrite-clj cljc work in progress:
```clojure
:deprecated-var
  {:exclude {rewrite-clj.zip/->root-string
             [rewrite-clj.regression-test]
             rewrite-clj.zip/->string
             [rewrite-clj.regression-test]
             rewrite-clj.zip.whitespace/append-newline
             [rewrite-clj.zip.whitespace-test]
             rewrite-clj.zip.whitespace/prepend-newline
             [rewrite-clj.zip.whitespace-test]
             rewrite-clj.node/value
             [rewrite-clj.zip.base]}}
```
One thing I was hoping for is the option of function level granularity in addition to ns granularity for the "from" part.  

Your solution works fine for my test code because I can reorganize all deprecated functions to a test ns and exclude for that ns.  (If I really cared).

For my API, I'd like to state that it is only ok to call my deprecated fn from only this (or maybe these) function(s) in my API ns.  For my current use case this is the portion of interest:
```clojure
:deprecated-var
  {:exclude {rewrite-clj.node/value
             [rewrite-clj.zip.base]}}
```

I'm note sure how you'd express it, but this is equivalent to what I'd like for my current use case:
```clojure
:deprecated-var
  {:exclude {rewrite-clj.node/value
             [rewrite-clj.zip.base/value]}}
```

I suppose, I could work-around this granularity issue by delegating `rewrite-clj.zip.base/value`'s body to `rewrite-clj.zip.base.deprecated/value` and then `:exclude {rewrite-clj.node/value [rewrite-clj.zip.base.deprecated]}`, but that seems a bit awkward.

Whadyathink?

**Comment by borkdude** [comment]
@lread It seems you want that more fine-grained config to solve this:

```
(defn ^{:deprecated "0.4.0"} value
  "DEPRECATED. Return a tag/s-expression pair for inner nodes, or
   the s-expression itself for leaves."
  [zloc]
  (some-> zloc z/node node/value))
```

Maybe a nicer solution is to not emit a warning when you call a deprecated function inside a deprecated function?

**Comment by lread** [comment]
Yes, exactly, but maybe more specifically (or maybe ideally?): not emitting a warning when calling my project’s deprecated functions from my project’s deprecated functions.

**Comment by borkdude** [comment]
@lread This version supports `foo.bar/baz` in the vector as well. a regex can also be used to match functions in which the deprecated function is used now. So:

```
{:linters
 {:deprecated-var
  {:exclude {foo.foo/deprecated-fn
             [foo.bar foo.baz/allowed "foo.baz/ign\\.*" "bar\\.*"]}}}}
```

**Comment by lread** [comment]
That works well for me @borkdude!  

I don't see the potential confusion with exclusion yet (I'm wondering about the regexes though, did you mean to escape the period?). To confirm my understanding of the intent of your example, we are saying: please don't warn me when deprecated function `foo.foo/deprecated-fn` is called form any of:
- namespace `foo.bar`
- function `foo.baz/allowed`
- functions starting with `foo.baz/ign`
- namespaces staring with `bar.`

I suppose if I were reading the config without clj-kondo docs, I might wonder a bit, which is probably what you are telling me.  A more self-documenting config might add extra keywords?
```clojure
{:linters
 {:deprecated-var
  {:exclude {:call-to foo.foo/deprecated-fn
             :from [foo.bar foo.baz/allowed "foo.baz/ign\\.*" "bar\\.*"]}}}}
```

**Comment by borkdude** [comment]
What I meant was usage in a definition vs. a call:

```
(ns foo.bar)
(defn baz [] (deprecated-fn))
```

vs.

`(foo.bar/baz (deprecated-fn))`

Right now I can't think of any reason why you would suppress a deprecation warning in a specific function call, so I think the current config makes sense. I'd like to avoid the keywords, but that's just preference.

**Comment by lread** [comment]
Ah, right, I see. Your example helped, thanks.  

I can't currently see a reason to suppress in a specific function call either.

Yes, the keywords are subjective and could be considered noisy - and the docs will explain.

So, in summary, this works splendidly, at least for me!

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/5049106dc19b912b5ea37bd68386bcc0a4d2e8bf

**Comment by borkdude** [comment]
@lread This is the latest master branch version:

https://4555-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.07.06-alpha-SNAPSHOT-macos-amd64.zip

**Comment by lread** [comment]
Thanks @borkdude, this is so very cool, I shall try it out today and get back to you.

**Comment by lread** [comment]
Ok found some time to give it a whirl!  In short 👍.

**Tested against**
- binary: https://4571-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.07.06-alpha-SNAPSHOT-macos-amd64.zip
- jvm: with `deps.edn` pointing to latest commit as of this writing: 1ba464a5687607bcdca9fdf7d91bdd62c72bc34d

**Observations**
I found no issues with the fix, but noticed the following while testing against my rewrite-clj cljc work in progress and doing ad-hoc tests:
- `import-vars` not supported - [already a git issue for that](https://github.com/borkdude/clj-kondo/issues/237)
- `ns` not supported, for example: \
`(ns ^{:deprecated "0.5.0"} rewrite-clj.dontusemenomore)` \
do people do this?
- works on macros too, cool!
- does not work on protocols
- found 4 more deprecation warnings than on my [first run](https://github.com/borkdude/clj-kondo/issues/338#issuecomment-510647344).  Awesome!

**Tangential ideas**
While testing, my mind was spit-balling ideas related to deprecation:
- maybe also consider an element deprecated if its docstring starts with the text `DEPRECATED`
- out of scope for clj-kondo but would be nice to know if using
    - a library [marked as deprecated on clojars](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar)
    - a deprecated Java/JavaScript function

**Also of interest**
Stumbled upon (maybe stale) https://searchcode.com which offers searching for terms with punctuation, which is handy for searching for Clojure code with `:deprecated`.

**Comment by borkdude** [comment]
@lread Thanks! The remaining comments will be processed in a feature version of clj-kondo.
