### ISSUE TITLE
Documentation on cljdoc.org is messed up

### ISSUE THREAD

**Issue by pgj** [borkdude/clj-kondo#357]
The documentation at https://cljdoc.org/d/clj-kondo/clj-kondo/2019.07.17-alpha/doc/configuration has git conflict markers inlined starting from section titled "Exclude deprecated var usage from being reported".  Note that the [source](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md) does not seem to be affected, so it might be a problem with the build / deployment.

**Comment by martinklepsch** [comment]
For now you'd have to publish a new release to update the documentation. :)
