### ISSUE TITLE
output dependency graph

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#371]
Since clj-kondo knows about var definitions and usages, it could output a graph of this information.

**Comment by daemianmack** [comment]
Would this allow for something like the graphviz namespace usage graph, only at the function call level? I'd love to see that.

**Comment by borkdude** [comment]
@daemianmack You can eat your heart out with https://github.com/borkdude/clj-kondo/issues/373 which I'm currently working on. 

Preview:
- data https://github.com/borkdude/clj-kondo/tree/dump-analysis/analysis#data
- namespace graph: https://github.com/borkdude/clj-kondo/tree/dump-analysis/analysis#namespace-graph

If you want to test this out before a release, just use the branch via clojure CLI + JVM and read the examples. If you want a binary instead, just let me know.

**Comment by borkdude** [comment]
Implemented at https://github.com/borkdude/clj-kondo/tree/master/analysis#namespace-graph.
