### ISSUE TITLE
Publish uberjar

### ISSUE THREAD

**Issue by jlesquembre** [borkdude/clj-kondo#414]
Thanks for writing clj-kondo, I find it really useful.

I'm trying to create a package for [NixOS](https://nixos.org/), compiling it with GraalVM, and it would be helpful if for the next release you can publish the uberjar on github.

That's because on NixOS, during the package build phase, the build process has no network access (and lein cannot connect to the maven repositories to download the dependencies). There are workarounds, but the simplest solution will be to use the uberjar.

**Comment by borkdude** [comment]
That seems an easy thing to add to the release process, so will do.

**Comment by jlesquembre** [comment]
Thanks!

**Comment by borkdude** [comment]
On second thought:

I was wondering about nixOS, isn't one of the ideas to have a reproducable build from the source?
If you start from the uberjar, you might as well start from the binary?

**Comment by jlesquembre** [comment]
yes, one of the main ideas of NixOS is to have reproducible builds. Ideally, it would be possible to build from the source, but java (and clojure) is not well supported on NixOS. Many, if not all, java packages are build from the the uberjar. I think there were some plans to improve java support, but not sure about the current status

I already tried to use the binary you publish, but it doesn't work on NixOS. In general, binaries compiled on other Linux systems don't work on NixOS. As far as I can tell, it's because of how shared libraries and dynamic links are managed on NixOS.

Recently, a new NixOS GraalVM version was released, and I was able to compile clj-kondo from the uberjar.

**Comment by borkdude** [comment]
@jlesquembre That clarifies it for me. It's awesome you want to make it work on nixOS, thank you.

**Comment by jlesquembre** [comment]
@borkdude sure, I already though about it, I'll create a PR once the package is on NixOS

**Comment by borkdude** [comment]
@jlesquembre I included a standalone .jar in this release now: https://github.com/borkdude/clj-kondo/releases/tag/v2019.07.31-alpha so you can already test with this.

Note that https://github.com/borkdude/clj-kondo/blob/master/resources/CLJ_KONDO_RELEASED_VERSION

always contains the most recent released version (a manual installer script also relies on this), but of course you can also use the Github API to fetch the latest version tag.

**Comment by jlesquembre** [comment]
@borkdude Thank you, it works perfectly :) I'll create a PR to add clj-kondo to NixOS and once gets accepted, I'll make a PR to the installation manual

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/34ee8736045e14e0b2e5109010793f48c1def132
