### ISSUE TITLE
Question: config.edn per project or global?

### ISSUE THREAD

**Issue by didibus** [borkdude/clj-kondo#421]
The docs mentions a config.edn file cxan be used in .clj-kondo , but this as I understand is a global setting. What if I want a per project setting which I can commit to version control and share with my project? Would there be a way to say add a config.edn file at the project root?

**Comment by didibus** [comment]
Hum, nevermind I see that it is actually per project already, based on user.dir. So it there no option to have a global config then?

**Comment by borkdude** [comment]
@didibus That's correct and by design. A config.edn belongs to a project and it meant to be shared with other people who are working on that project, so you have the same conventions and no incomplete config scattered over multiple places.

**Comment by borkdude** [comment]
@didibus Having said that, you can do some additional configuration with `--config`. See https://github.com/borkdude/clj-kondo/blob/master/doc/config.md.
