### ISSUE TITLE
Snap package is discontinued.

### ISSUE THREAD

**Issue by metasoarous** [borkdude/clj-kondo#424]
**version**

clj-kondo v2019.07.31-alpha

**platform**

Linux (Ubuntu 19.04), with Vim 8.1

**problem**

Every file I open only comes with only a single annotation at the level of the ns declaration, and hovering over displays the message `error: file does not exist`.

**repro**

Not sure how to reproduce on another system at this point, but here's how I setup:
* Installed ale by adding `Plugin 'dense-analysis/ale'` and `let g:ale_linters = {'clojure': ['clj-kondo']}` to my `~/.vimrc` (and running `:PluginInstall`).
*  Istalled `clj-kondo` using the Linux snap (`sudo snap install clj-kondo && sudo snap connect clj-kondo:home`)

**expected behavior**

That correct namespace declarations should look fine, and that other usage errors trigger notifications.

**actual behavior**

As described in problem; only the ns declaration gets an error notification.

I can however get reasonable annotations when I run from the command line, like `clj-kondo --lint some/clj/file.clj`

**Comment by borkdude** [comment]
When I read the title of this issue I already suspected you installed using Snap. The snap install cannot see files outside of user directory. Are your files in your user directory, and if so where?

**Comment by metasoarous** [comment]
Yes, they are in my user directory (well, in a subdirectory: `~/code/<project-name>/src/*`). I can try installing using one of the other methods, but is there anything it would be helpful for me to try first?

**Comment by borkdude** [comment]
@metasoarous Given that the snap package often causes confusion, since it has limited access, I've decided to discontinue the snap package. Please select a different installing method. For linux you can either use brew for linux, or the [manual installer](https://github.com/borkdude/clj-kondo/blob/master/doc/install.md#installation-script-macos-and-linux).

**Comment by borkdude** [comment]
Or if you're using Arch linux, there's a .aur package.

**Comment by borkdude** [comment]
Note to self: announce that the snap package is deprecated from the next release on.

**Comment by metasoarous** [comment]
Yay! Works with Homebrew/Linuxbrew. Thanks again!
