### ISSUE TITLE
Level is not supported in inline configs

### ISSUE THREAD

**Issue by Macroz** [borkdude/clj-kondo#430]
clj-kondo v2019.07.31-alpha (and master)

Level configuration is not possible to use in namespace inline config. Static file config for levels is used instead. This test case for example describes the expected behavior. Level based filtering is done in code where the namespace config is not available.

```
index 5d1f69a..e84142f 100644
--- a/test/clj_kondo/main_test.clj
+++ b/test/clj_kondo/main_test.clj
@@ -1155,7 +1155,12 @@
   (is (empty? (lint! "(ns ^{:clj-kondo/config
                             '{:linters {:unused-namespace {:exclude [bar]}}}}
                           foo
-                        (:require [bar :as b]))"))))
+                        (:require [bar :as b]))")))
+  (is (empty? (lint! "(ns ^{:clj-kondo/config
+                            '{:linters {:unused-namespace {:level :off}}}}
+                          foo
+                        (:require [bar :as b]))")))
+  )
```

**Comment by borkdude** [comment]
@Macroz Thanks for posting this issue. I'll consider it for a next release.

**Comment by borkdude** [comment]
This specific example has been fixed with https://github.com/borkdude/clj-kondo/commit/b22d4d902a43a7ad4782b4bb775d8ceccffb2ea5.

The code is now in a better position to support other linters via ns metadata as well, but examples would be most welcome.
