### ISSUE TITLE
Support cljs.test/async macro

### ISSUE THREAD

**Issue by kommen** [borkdude/clj-kondo#444]
https://cljs.github.io/api/cljs.test/async

```
echo '(cljs.test/async done (done))' | clj-kondo --lint -
<stdin>:1:18: info: unresolved symbol done
linting took 13ms, errors: 0, warnings: 0
```

It would be nice to not warn about this by default as it is part of clojurescript.

**Comment by borkdude** [comment]
@kommen If you want, you can test this with the version from master.

```
clojure -A:clj-kondo --lint <your_code.cljs>
```

**Comment by kommen** [comment]
@borkdude works nicely for me, thanks! See you in Helsinki :)
