### ISSUE TITLE
Adding an auto import feature

### ISSUE THREAD

**Issue by iha2** [borkdude/clj-kondo#453]
Wouldn't it be cool in clj-kondo allowed you to auto import? I don't know if this is possible but I would love to see it. It would speed up adoption and development.

Let me know what you think.

**Comment by borkdude** [comment]
What do you mean by auto import? Can you be more specific?

**Comment by iha2** [comment]
Basically, if there is a form written in you application, clj-kondo can give you the list of possible forms that can be imported into the file, and fill them in the file if selected. Basically what an editor does. clj-kondo will simply do the heavy lifting, and editors can tie themselves to it. Does that make senes?

**Comment by borkdude** [comment]
I still don't know exactly what you mean. Do you mean auto-complete? Clj-kondo does not not offer editor-specific tooling, as it is agnostic about which editor you are using.

**Comment by iha2** [comment]
In VS code and javascript, if you write a function that is not in the file, it will give you the opportunity to import it. It's basically auto-complete with the added expectation that it will also add the import for what you want.

**Comment by borkdude** [comment]
And by import you mean `:require` + `:refer`? 

Currently clj-kondo can provide information about what is available in which namespace (after inspecting that namespace) by using the [analysis output](https://github.com/borkdude/clj-kondo/blob/master/analysis/README.md). It's up to the editor tooling people to write a plugin that uses clj-kondo for this.

**Comment by SevereOverfl0w** [comment]
refactor.el provides this functionality. It utilizes a project analysis to know that when you type str/includes? you mean clojure.string (because there are other requires using clojure.string).
