### ISSUE TITLE
Add custom linters

### ISSUE THREAD

**Issue by SevereOverfl0w** [borkdude/clj-kondo#468]
**Is your feature request related to a problem? Please describe.**

It's a high barrier to entry when creating new linters based on the clj-kondo analysis data to create an entire release process and convince users to add it to their existing linting and tooling setup.

**Describe the solution you'd like**

Using Sci would allow a fast way to write small linters that users could drop into their .clj-kondo folder.

**Describe alternatives you've considered**

- Doing my own release.

**Additional context**

These new linters would produce outputs that kondo would print.

**Comment by borkdude** [comment]
This is a cool idea, but I think we need more details and at least a few examples of how this could work. I'll keep this as an idea for now.  In the spirit of "no is temporary and yes is forever" I'm holding off on this for now, as this will mean implementing APIs that can be hooked in with sci that will have to be supported forever and it may be a little bit too soon to do that right now. I think the quickest way of getting something similar is using the clj-kondo analysis export. You can include kondo as a test dependency and then implement the extra linter as a clojure.test test that either fails or prints warnings possibly combined with a delay. This way your team members get feedback without having to setup extra stuff in their dev environment.

**Comment by vemv** [comment]
(Coming here redirected from #745)

> This is a cool idea, but I think we need more details and at least a few examples of how this could work. 

#745 suggests one possible shape (one passes functions, said functions receive data from Kondo). A given function would be invoked N times, one per file to be linted.

(passing a `fn` in JVM kondo is trivial... perhaps for more typical usages, not so much?)

I guess that the argument to be received by this callback could be a map with entries such as `:filename, :file-contents, :ast` etc. Whatever made the linting of a given file reasonably easy.

> I think the quickest way of getting something similar is using the clj-kondo analysis export

Does clj-kondo use that same kind of input in its own linters? (It could feel limiting if kondo linters had access to more info than users' linters)

**Comment by borkdude** [comment]
Just adding this for reference:

clojure-lsp uses a DSL to describe custom macros:

https://github.com/snoe/clojure-lsp/#macro-defs

**Comment by yenda** [comment]
Not sure if that is why you mean by needing an example but I stumble upon this issue looking for a way to add a custom linter. Our use case is that we want to make sure all uses of re-frame.core/dispatch function are dispatching events that use a namespaced keyword.

**Comment by borkdude** [comment]
@yenda That's a good example. I actually thing the macroexpand feature could be used for this as described in https://clojureverse.org/t/feedback-wanted-on-new-clj-kondo-macroexpansion-feature/6043. But instead of macroexpanding you just want a hook to do some checks and then continue the linting right? Which is slightly different, but maybe with some generalization this can be captured under the same feature.

**Comment by borkdude** [comment]
@yenda One alternative could be to enhance the analysis output the sexpr of the call in `:var-usages`:

https://github.com/borkdude/clj-kondo/tree/master/analysis

**Comment by borkdude** [comment]
Here's an example:

<img width="563" alt="Screenshot 2020-06-17 23 43 42" src="https://user-images.githubusercontent.com/284934/84954038-f52b8400-b0f4-11ea-8d34-da78f8244ff8.png">

**Comment by borkdude** [comment]
Here's an example:

<img width="825" alt="Screenshot 2020-06-18 00 32 27" src="https://user-images.githubusercontent.com/284934/84957401-68d08f80-b0fb-11ea-8ee3-7e296047dd05.png">

**Comment by borkdude** [comment]
https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#hooks is now one way of writing custom linters.
