### ISSUE TITLE
Store jar file location in analysis data?

### ISSUE THREAD

**Issue by sogaiu** [borkdude/clj-kondo#474]
**Is your feature request related to a problem? Please describe.**

Tools that index Clojure source code such as ctags don't appear to really understand Clojure and employ methods involving regular expressions to determine various identifiers.   The results are usable in some cases, but fall short in others.  AFAIU, it also appears to be less common to index the dependencies of a project, possibly especially for information within jar files.

clj-kondo appears to understand Clojure source pretty well with potential for further improved understanding.  It already determines most of the information necessary in its analysis to generate good index files of a project AND its dependencies.

However, it doesn't appear to quite store / obtain everything necessary.  

One missing piece appears to involve the full locations of definitions of things within jar files.  Some examination of sample analysis data suggests that paths relative to jar file roots are recorded, but not the actual paths to the jar files themselves.

For example, one jar file on the example's classpath was essentially:

```
/home/alice/.m2/repository/com/wsscode/pathom/2.2.7/pathom-2.2.7.jar
```

However, within the analysis, for a defintion for something in the  jar, an associated path was:

```
com/wsscode/pathom/parser.cljc
```

but I did not find the path to the corresponding jar file in the analysis data.

**Describe the solution you'd like**

It would be nice for the full paths to the jar files to be available in the analysis data.

A separate program (perhaps using rewrite-clj) could post-process the analysis data and visit all of the analyzed files to produce a TAGS file (or possibly multiple files).

In the case of Emacs on Linuxen, experiments suggest it can handle paths (via TRAMP) that look like:

```
/home/alice/.m2/repository/com/wsscode/pathom/2.2.7/pathom-2.2.7.jar/com/wsscode/pathom/parser.cljc
```

even within TAGS files.  It seems that an appropriately created TAGS file using clj-kondo's analysis with a project's `clj -Spath` output would give the ability in Emacs to use M-. (roughly, jump-to-definition) [1] to visit appropriate locations within dependency source files even within jars.

__In short, jump-to-definition across one's project files AS WELL AS its dependencies.__

I haven't verified, but IIUC, TRAMP's ability to directly visit files within archives does NOT currently work on macos or Windows as it depends on gvfs.

In the short term, it's conceivable that there might be a utility that arranges to uncompress (portions of?) jar files that are on the classpath to a suitable location so that copies of contained source files might be visited directly.  By performing a straight-forward modification to the TAGS file (to point at files in the uncompressed location instead of directly within jar files), Windows and macos might also be made to work.

In any case, it would be helpful to have the jar file locations recorded for each definition -- perhaps as an option to request that it's recorded?  May be it is better for that information to have its own key-value pair instead of being stored as the corresponding value of the :filename key.  Possibly a value corresponding to a :root-dir key?

**Describe alternatives you've considered**

1. Try to write a program that visits all of the relevant parts of `clj -Spath`, extract information, and build a TAGS file.

2. Try to write a program that tries to match up the paths in the analysis data with jar file paths.

For the "extract information" part of 1, accurately deducing definitions of things seems like what clj-kondo already does, so this appears to be duplication of effort.

For 2, it seems possible that in some cases one would not be able to unambiguously create the correct associations between paths within jar files and actual jar files.  IIUC, the classpath at the time of analysis is not recorded [2] so the path information that is recorded in the analysis may not be enough to determine exactly which file is being referred to by the corresponding value of a given :filename key.

If clj-kondo does learn (or knows) what the (internal-to-jar) path <-> jar file path associations are, attempting to determine this in another fashion also seems like duplication of effort.

**Additional context**

[1] It turns out that the default set-up for M-. doesn't play well with namespace- / alias-prefixed identifiers in Emacs at the moment, but there is a work-around for this:

https://github.com/candera/emacs/blob/f18df4f325c526f5d8cb66180240f5d270523cbb/init.el#L1254-L1264

[2] Perhaps an option to request that the classpath is also recorded in the analysis is in order?

**Comment by borkdude** [comment]
@sogaiu Can you try with this option? https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#output-canonical-file-paths

**Comment by sogaiu** [comment]
Thanks!

Looks pretty good so far.
