### ISSUE TITLE
False positive: `conj` is not accepting sequential as the first argument

### ISSUE THREAD

**Issue by mynomoto** [borkdude/clj-kondo#489]
**version**
clj-kondo v2019.09.22-alpha

**platform**
linux

**problem**
`clj-kondo` is returning a false positive 

**repro**
`(conj (flatten []) {})`

**expected behavior**
Should not be a linter error

**actual behavior**
`xxx.clj:1:7: error: Expected: collection, received: sequential collection.`

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/e0f499ca39cc0941d8f016bd75edb29a7608949c.

**Comment by mynomoto** [comment]
Thanks!
