### ISSUE TITLE
Show a proper error message for unmatched Parentheses 

### ISSUE THREAD

**Issue by marcomorain** [borkdude/clj-kondo#514]
**Is your feature request related to a problem? Please describe.**
`clj-kondo` warns about unmatched parentheses in the same way as Clojure core – the error referers to unexpected EOL at the end of the file, instead of highlighting the brackets that don't match.

**Describe the solution you'd like**
I'd like `clj-kondo` to emit 2 errors when the parens are unbalanced.

**Describe alternatives you've considered**
I've not considered any - feedback welcome.

**Additional context**
I've just spent 5 minutes trying to find the reason that code would not compile.

### Example 1: Simple missing paren

```Clojure
(defn function-with-no-closing-brace []
  (inc 5)
```

Actual output:
```
server_test.clj:65:1: error: Unexpected EOF.
```

This error message gives a location at the end of the file, _not_ where the unmatched paren is located. The error message does not mention that a paren is unmatched, it says that it got an "unexpected EOF".

The red squiggle in VSCode produced from this error is equally unhelpful:

![image](https://user-images.githubusercontent.com/448001/66387600-31caab80-e9bc-11e9-9955-971d2aea0d82.png)

Expected Output:

```
server_test.clj:60:1: error:Unmatched opening-paren `(`
server_test.clj:65:1: error: Reached end-of-file while trying to read the `)` to close the opening paren on line 60 column 1
```

### Example 2: Badly nested parens of different types

```Clojure
(defn make-basic-service
  []
  (grpc-server/gen-service
    (UserServiceGrpc/getServiceDescriptor)
    UserServiceGrpc$UserServiceImplBase
    {:get-user (fn [req]
                 (if (= {:account-id (UUID/fromString "8f1e7316-293e-4946-99ee-c5ea74e01a5c")
                         :user-id (UUID/fromString "7c662690-cd61-4e37-939b-4727548d95b4")}
                        (select-keys req [:account-id :user-id]))
                   (assoc (select-keys req [:account-id :user-id]) :display-name "cookie monster")
                   (throw (-> (Status/NOT_FOUND)
                              (.withDescription "user not found")
                              .asRuntimeException))))
     :always-fail (fn [_req]
                    (throw (ex-info "a specific problem" {:status :resource-exhausted})))))
```

Output in VSCode:

![image](https://user-images.githubusercontent.com/448001/66388304-b4079f80-e9bd-11e9-8519-f63435901162.png)

Note that the red error highlights a closing paren, which makes it look like there are too many closing `)`, which is not the case. The problem is with the `{` on line 20.

Actual output:
```
server_test.clj:29:90: error: Unmatched delimiter: )
```

Expected Output:

```
server_test.clj:20:4: error: Unmatched opening `{`
server_test.clj:29:90:4: error: Unmatched parentheses - found a closing `)` when expecting to match the `{` opened on line 20:4
```
```

**Comment by borkdude** [comment]
It might be worth looking into this unfinished PR: https://github.com/borkdude/clj-kondo/pull/418
