### ISSUE TITLE
The :type-mismatch linter runs even in contexts where :invalid-arity is turned off

### ISSUE THREAD

**Issue by imrekoszo** [borkdude/clj-kondo#547]
**version**

clj-kondo v2019.10.11-alpha

**platform**

os x

**problem**

The `:type-mismatch` linter runs even in contexts where `:invalid-arity` is turned off, for example by https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#exclude-arity-linting-inside-a-specific-macro-call

This is problematic as although there is a way to fine-tune where arity checks will be executed, type checking can only be tuned/turned off globally due to its available settings and https://github.com/borkdude/clj-kondo/issues/430

If the user decided to disable arity checking for a context, that is probably because the macros used in the code are either manipulating arguments passed to a function, or use a form that appears to be a function call, for purposes other than actually calling the function (mocking etc.). 

**repro**

Please see https://github.com/borkdude/clj-kondo/pull/548/files#diff-6db85441b1dbbf3b7e4f5db79136ede1R87

**expected behavior**

Argument types don't get checked when arity check gets skipped.

**actual behavior**

Argument types do get checked.

**Comment by borkdude** [comment]
@imrekoszo I'm beginning to think there should be an all-in-one setting to turn off all relevant linters to avoid false positives in macros. So something like `:ignore-calls [foo/bar]` where you put the fully qualified names of the macros and when called unresolved symbols, arity errors, private var usage and type checking errors will be ignored. What do you think? It might also be a nice feature for tooling to automatically add these symbols to this entry in the configuration file (cc @PEZ).

**Comment by PEZ** [comment]
A master switch is nice if I can also fine tune. Well, even if I can't fine tune, but with fine-tuning it would be extra nice.

As for tooling. Yes, some sort of help for the user to at least know where to tune the listing. Maybe [this issue](https://github.com/borkdude/clj-kondo.lsp/issues/2) on `clj-kondo.lsp` is relevant here.

**Comment by imrekoszo** [comment]
> What do you think?

I have a short term and a long term answer :) Let me start with the short term one:

Currently the only way to not get false positive errors for the repro cases I submitted is to globally turn down the `:level` of `:type-mismatch`, even if the false positive only occurs in a single place. This causes us problems in a few projects as we would prefer to have the linter at `:error` level everywhere else but a few places. On the other hand, the flexibility of config options for `:invalid-arity` are quite nice and we managed to come up with a satisfactory tuning.

Why I'm proposing the changes that are in my PR now is because the two linters are already connected as of the latest version, as shown by this line: https://github.com/borkdude/clj-kondo/pull/548/files#diff-a0f7c1f7683ffc1de22015480c7ce38dL327 - both linters examine the arguments passed to a call, and I believe the intent of that line is that if we already established that the number of args is incorrect, we shouldn't bother checking the types. That line doesn't take into account however the case where we completely skip checking the arity. In my opinion the two linters are really two strictness levels of the same thing and I think it is appropriate to skip the stricter one if the less strict one is also being skipped.

I also didn't want to propose any significant structural changes due to my lack of time and lack of knowledge of the direction you want to take in the long term. This change, if released, would be helpful to our team.

Now on to the long term idea.

Linting macros is always going to be problematic due to their Turing-completeness. However I'd argue that simply turning off certain linters inside a macro is probably a little too blunt in the long term. It will cover a lot of cases of course but there are macros (along the lines of `let`, for example) where you'd want certain linters off/on in different args to the macro itself. For example a macro that sets up mocks in its first argument and uses those (with-redefs for example) when executing the 'body' passed to it. All sorts of nasty things can happen with the contents of the first arg so we should probably skip most linters there, but the 'body' should still be linted as normal code.

I use Cursive for development and, like clj-kondo, it does quite a bit of static analysis/linting. Both have a `lint-as` functionality which helps with a lot of cases I described above. What I would love to see in the long term is a generalisation of the `lint-as` functionality. I'm not sure how this is currently implemented in either of these projects but if there was a way to describe the structure of a macro at least to some extent in a reusable way, that would open up a lot of possibilities.

With regards to tooling support (and let me CC @cursive-ide here) it would be extremely awesome if these macro description data structures could be shared by both projects (and other static analysers/linters I'm not aware of). Just as the recent addition of the `.nrepl.edn` support to Cursive, this could provide a way of setting macro interpretations up in a portable way. Heck, macro authors could even put these into the metadata of their macros.

**Comment by borkdude** [comment]
> Both linters examine the arguments passed to a call, and I believe the intent of that line is that if we already established that the number of args is incorrect, we shouldn't bother checking the types.

I agree, thanks.

As for the macro description data structures: this has been in the back of mind for a while and that would indeed be useful. Welcome to open a new issue for this and post ideas/proposals there.

**Comment by imrekoszo** [comment]
Thank you very much for the merge. I'll have a think about the macro topic and try to come up with a starting point for an issue.
