### ISSUE TITLE
Merging default unresolved symbols with custom ones doesn't work when using the same namespace

### ISSUE THREAD

**Issue by danielcompton** [borkdude/clj-kondo#608]
**version**: clj-kondo v2019.11.07
**platform**: macOS, Homebrew
**editor**: N/A
**problem**

I have defined custom `unresolved-symbols` config for `clojure.test/is` to include a custom `clojure.test/assert-expr`. This custom unresolved symbol conflicts with the default config: https://github.com/borkdude/clj-kondo/blob/b9c4ba5ec9c4dacf708f83459686ab1e75c3549b/src/clj_kondo/impl/config.clj#L49

**repro**

config.edn

```edn
{:linters
 {:unresolved-symbol
  {:exclude [(clojure.test/is [x-not-thrown?])]}}}
```

repro.clj

```
(ns my.api.repro
  (:require [clojure.test :refer [deftest is]]))

(deftest period-doesnt-support-time
  (is (thrown? Exception
               (ex-info "Uh oh" {}))))
```

```console
$ clj-kondo --lint test/my/api/repro.clj
test/my/api/repro.clj:5:8: error: unresolved symbol thrown?
linting took 28ms, errors: 1, warnings: 0
```

This isn't needed to repro, but might help explain the motivation for this bug fix better:

```clojure
(defmethod clojure.test/assert-expr 'x-not-thrown? [msg form]
  ;; (is (not-thrown? c expr))
  ;; Asserts that evaluating expr doesn't throw an exception of class c.
  ;; Returns the exception thrown.

  ;; This is the inverse of thrown? from clojure.test
  ;; There is no namespacing possible here, so we prefix with `x-` to
  ;; avoid any collisions.
  (let [body (next form)]
    `(try ~@body
          (clojure.test/do-report {:type :pass, :message ~msg,
                                   :expected '~form, :actual nil})
          (catch Throwable e#
            (clojure.test/do-report {:type :fail, :message ~msg,
                                     :expected '~form, :actual e#})
            e#))))
```

**expected behavior**

No linting errors, clj-kondo marks `thrown?` as safe to ignore when linting in side `clojure.test/is`.

**Comment by borkdude** [comment]
Not merging can also seen as a feature, as in: I know something better than the default configuration?

What about doing the merge yourself as in:

```
{:linters
 {:unresolved-symbol
  {:exclude [(clojure.test/is [thrown? thrown-with-msg? x-not-thrown?])]}}}
```

I'm not 100% sure what the best solution is yet, but this seems a small price to pay?

**Comment by danielcompton** [comment]
> I'm not 100% sure what the best solution is yet, but this seems a small price to pay?

Yeah this is what I’ve done in the meantime. It’s a pretty niche use-case, it doesn’t seem like a high-priority.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/b4b5d689fccff5bb59b408c9773cfb815f360958.
