### ISSUE TITLE
:lint-as macro with arbitrary length vector?

### ISSUE THREAD

**Issue by joncol** [borkdude/clj-kondo#612]
**version**

`clj-kondo v2019.11.07`

**platform**

Arch Linux

**editor**

Emacs

**problem**

Are there any Clojure core macros that you can use with `:lint-as` for `me.raynes.conch/with-programs`? The example `config.md` contains examples for both `programs` and `let-programs`, but not `with-programs`. The latter takes a vector argument of arbitrary length.

The relevant lines from the example `config.md`:
https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#L128-L129

**Comment by borkdude** [comment]
I don't think there currently is a built-in macro that is exactly like this, so `:lint-as` probably doesn't work. You can use `{:linters {:unresolved-symbols {:exclude [(me.raynes.conch/with-programs)]}}}` to disable the unresolved symbols linter in a call to `with-programs`.

**Comment by arichiardi** [comment]
Had the same question, `with-programs` is weird cause it binds the symbol in the vector so it does not really look like something "known" (at least to me) like a `let`:

```clojure
(sh/with-programs [liquibase] (apply liquibase (conj args {:out *out* :buffer :none})))
```
