### ISSUE TITLE
`clojure.set/rename` is used but not the `clojure.set` ns is not required

### ISSUE THREAD

**Issue by raymcdermott** [borkdude/clj-kondo#613]
Certain tools eg the REPL auto require `clojure.set` so it's not obvious that you have not required the namespace until runtime.

Please provide a warning something like:
`clojure.set/rename` is used but not the `clojure.set` ns is not required

I would be happy to help make the PR so please suggest an approach and I'll do the necessary

**Comment by borkdude** [comment]
Duplicate of https://github.com/borkdude/clj-kondo/issues/339
