### ISSUE TITLE
Revert #618

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#630]
If this doesn't have any added benefit for VSCode and @eraserhd will not use it anymore, we can maybe deprecate this behavior again.

**Comment by borkdude** [comment]
@eraserhd fwiw, I think emacs does the following: it saves the intermediate state of a file to a tmp file and then invokes the linter piping the input from the tmp file to stdin

so clj-kondo only sees the path "stdin", not even the filename
so in that case the new feature isn't very beneficial. however I think in the case of VSCode marco morains plugin, it's invoked on save and then using the filename, so it works for that case

**Comment by eraserhd** [comment]
So I'm officially not going to use it.  I'm using a work-around for setting the working directory before running clj-kondo, and I'm going to try to add official support to Kakoune to replace the work-around.

**Comment by borkdude** [comment]
Thanks, I reverted the code.
