### ISSUE TITLE
Metadata for skipping expressions

### ISSUE THREAD

**Issue by sanel** [borkdude/clj-kondo#633]
**Is your feature request related to a problem? Please describe.**
Apologies if this was already addressed, I wasn't able to find it in documentation. It would be nice if there is a way to explicitly skip (in code) expressions from linting, no matter what expression is.

Manually editing `config.edn` can be cumbersome sometimes.

**Describe the solution you'd like**
It would be nice to say:

```clojure
(try
  (catch Exception ^:skip-lint e))

;; or to skip everything in block
(defn ^:skip-lint foo [a b]
  ...)
```

**Comment by borkdude** [comment]
One reason I haven't supported this yet, is point 6 here:

https://github.com/borkdude/clj-kondo/blob/master/doc/dev.md#design-principles

**Comment by borkdude** [comment]
Another reason could be: ignoring some forms can lead to even more warnings which should then also be ignored:

```
^:clj-kondo/ignore (defn foo [])
(foo) ;; warning
```

**Comment by sanel** [comment]
Make sense. Thanks for quick response.
