### ISSUE TITLE
support schema.core/defrecord

### ISSUE THREAD

**Issue by barkanido** [borkdude/clj-kondo#637]
Since clj-kondo already supports several `schema.core` macros out-of-the-box it would be nice to also support `schema.code/defrecord` automatically.
Neither: `{:linters {:unresolved-symbol {:exclude [(schema.core/defrecords)]}}}` nor `{:linters {:lint-as {schema.core/defrecord clojure.core/defrecord}}}` satisfies the linter.

I am not sure if the default behavior should be ignoring it altogether or treat is as a `defrecord`, and ignoring the `:- type` parts.

The current alternative is to shut down all related errors on it since kondo is pretty confused about it

**Comment by borkdude** [comment]
Thanks, will implement.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/70cfa5af43997a854d4b49bfd1ad1af83e93405f
