### ISSUE TITLE
Unresolved symbol js in valid CLJS code

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#647]
Repro:
```
(.log js/console ^js #js [1 2 3])
```

**Comment by andreyorst** [comment]
Maybe this should be considered different issue, but I still get `Unresolved namespace js. Are you missing a require?`

**Comment by borkdude** [comment]
@andreyorst Need more context. Are you using a .cljs file?

**Comment by andreyorst** [comment]
Yes, however I was fiddling with this issue for last 20 minutes, and it seems this is not an issue with clj-kondo itself, but flymake backend.
