### ISSUE TITLE
Consistent alias doesn't work when only requiring namespace without alias

### ISSUE THREAD

**Issue by Heliosmaster** [borkdude/clj-kondo#650]
v2019.11.23

Native / macOS

**problem / repro**

In `config.edn` i have specified

```clojure
:consistent-alias {:aliases {datomic.api datomic}}
```
In one namespace I have

```clojure
(ns foo
  (:require [datomic.api]))
```
it shows: `Inconsistent alias. Expected datomic instead of .`

In this case, one might be requiring a ns only to load specs, for example, without providing an alias.  Since the alias is not used, adding it would throw another warning about unused alias 🤷‍♂

In addition, I have a similar case for a `:require-macros` instead of a simple `:require` 

**expected behavior**

"No alias" shouldn't be shown as inconsistent alias.

**Comment by borkdude** [comment]
Thanks! This seems like an easy issue to fix. If you're interested in doing a PR, let me know. Else I'll get to it hopefully soon.

**Comment by Heliosmaster** [comment]
> Thanks! This seems like an easy issue to fix. If you're interested in doing a PR, let me know. Else I'll get to it hopefully soon.

I'll take a look and let you know
