### ISSUE TITLE
Unresolved symbol for schema.core/defrecord auto-generated factory function

### ISSUE THREAD

**Issue by yaronel** [borkdude/clj-kondo#662]
When creating a record with [plumatic/schema](https://github.com/plumatic/schema), for example  `(s/defrecord Foo [])`, Clojure creates two factory functions:
`map->Foo` and `->Foo`.
clj-kondo accepts `->Foo`, but complains about the `map->Foo` as unresolved symbol.
```
info: unresolved symbol map->Foo
```
Using `RELEASE` version 2019.12.14

**Comment by liuchong** [comment]
Which release fixed this issue? It seems still warning on this.

**Comment by borkdude** [comment]
The release that went out after January 10th I guess.

I still see this working with 2020.07.29:

``` clojure
(require '[schema.core :as s])
(s/defrecord Foo [])

map->Foo ->Foo
```

**Comment by brianium** [comment]
This seems to affect any record type defined by a macro.

```clojure
;; Defines a record named DevConsumer via defrecord
(defconsumer DevConsumer "dev"
  [message _]
  (println message))

;; Unresolved symbol ->DevConsumer
(->DevConsumer a b c d)
```

Is there a simple way to prevent this behavior without explicitly mentioning the `->DevConsumer` symbol in config?

**Comment by borkdude** [comment]
@brianium Yes, you can write a simplified version of this macro using the `:macroexpand` hook.

See https://github.com/clj-kondo/clj-kondo/blob/master/doc/hooks.md. Let me know if you have any questions, by opening a Discussion here on Github.

**Comment by brianium** [comment]
@borkdude wow! Thank you 🙇🏻
