### ISSUE TITLE
No warning on non-existing aliases

### ISSUE THREAD

**Issue by Saikyun** [borkdude/clj-kondo#666]
**Is your feature request related to a problem? Please describe.**
When refactoring I find it useful to get warnings about non-existing aliases. If I move the code `(a/f)` from ns `x` to `y`, where `x` has `(:require [alpha :as a])` and `y` doesn't, I want a warning.

**Describe the solution you'd like**
I want a warning.

**Describe alternatives you've considered**
Automatically inserting the new require-declaration in ns `y` would be nice, but I think that be overly complicated to implement.

**Additional context**
https://memset.se/10528/abebd2b2afbbe500c567a066b4a1ca238f5738fc
Here's an example, where I can refer to `abc/cat` without the alias `abc` existing.

**Comment by Saikyun** [comment]
I might add that I'd be interesting in submitting a PR, but not sure where to start.

**Comment by borkdude** [comment]
Hi @Saikyun, I believe this is a duplicate of #546.

**Comment by Saikyun** [comment]
Ah, I see. I looked at #546 before and it wasn't quite the same. But #634 would cover this one. :)
