### ISSUE TITLE
lsp server capabilities

### ISSUE THREAD

**Issue by agzam** [borkdude/clj-kondo#672]
Not clear what lsp capabilities currently supported. I have attempted to use it, configured as documented, waited for it to successfully to connect.
Then tried `lsp-find-references` and it shows this message:

```
lsp-find-references: Capability not supported by the language server: "referencesProvider"
```

**Comment by borkdude** [comment]
The LSP server only provides diagnostics, same as the binary.

**Comment by agzam** [comment]
But isn't this a bit misleading for people expecting it to use as lsp-server? What's the long term plan here? Would you like kondo to become fully-fledged lsp-server as an alternative to https://github.com/snoe/clojure-lsp or do you think it would be better to integrate clj-kondo into that project?

related: https://github.com/snoe/clojure-lsp/issues/36

**Comment by borkdude** [comment]
@agzam I wouldn't mind if @snoe would integrate clj-kondo with clojure-lsp. In fact we discussed this on Slack and he agreed on this.

The rationale for the clj-kondo LSP server is:

- Some people cannot run the binary (this was Windows until not too long ago)
- VSCode people can install a package from the marketplace without installing any external dependencies except Java
- IntelliJ people now have an extra way of running clj-kondo and no longer depend on the FileWatcher plugin (which only works in commercial licenses)

Recently there was a person who tried the LSP server with emacs lsp-mode and it worked. So for whatever reason people want to use this, it's there for them to use. I don't think it's misleading.

**Comment by agzam** [comment]
Please don't get me wrong though: I said it might be misleading because clj-kondo is a project of incredible quality and naturally it might be expected for it to have better support for everything that clojure-lsp does, which in this specific case is not true. Maybe that can be emphasized in the docs.

**Comment by borkdude** [comment]
@agzam PR welcome!

**Comment by borkdude** [comment]
@agzam I added some notes to https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md. Please check if that's sufficient.

**Comment by agzam** [comment]
That's good. Thank you!
