### ISSUE TITLE
:refer :all on clojure.test is flagged as a warning

### ISSUE THREAD

**Issue by technomancy** [borkdude/clj-kondo#681]
**version**

2019.08.21-alpha

**platform**

Debian buster, openjdk version "1.8.0_232", lein master

**problem**

When you have `(:require [clojure.test :refer :all])` in your code, it gets flagged as a warning, despite the fact that the entire reason I added `:refer/:all` to `require` is to support using `clojure.test` seamlessly.

**repro**

    (ns kondo.repro
      (:require [clojure.test :refer :all]))

**expected behavior**

clj-kondo should not complain about this since it is perfectly acceptable code. Using `:refer` here is not a good choice because it means if you add or remove a `testing` block you would have to go make changes in the `ns` clause, and using an alias for `clojure.test` is contrary to widespread accepted style.

I can submit a PR to fix this.

**Comment by borkdude** [comment]
@technomancy Hey Phil, thanks for your amazing work with leiningen.

I propose implementing it as part of this feature: https://github.com/borkdude/clj-kondo/issues/560
for which a PR is welcome. People can then decide for themselves if they want to add `clojure.test` to this configuration. If you don't agree with this rule in general, you can turn it off with `{:linters {:refer-all {:level :off}}}'.
