### ISSUE TITLE
Variable usage in with-redefs binding is ignored in some cases

### ISSUE THREAD

**Issue by thobbs** [borkdude/clj-kondo#701]
**version**

v2020.01.10

**platform**

Native version on Linux

**problem**

The latest release of clj-kondo introduced some issues with how with-redefs is analyzed. Variables that are used on the left-hand or right-hand side of the binding clause can be ignored for the purposes of "unused binding" and "unused import" checks.

I suspect this was the commit that introduced this: https://github.com/borkdude/clj-kondo/commit/e5182730fecf24f8db27d6bd6dfad1c66137feca

**repro**

~~~clojure
(ns foo
  (:require [environ.core :refer [env]]
            [foo :refer [some-constant]]
            [utils.kafka :refer [send-message]]
            [utils :refer [fn-1 fn-2 fn-3 fn-4]]))

(defn ^:private mock-fn
  [& args]
  args)

(defn with-updated-system
  [f]
  (let [updated-env (assoc env :flag true)]
    (with-redefs [fn-1 (constantly identity)
                  fn-2 (constantly identity)
                  fn-3 (constantly identity)
                  fn-4 (constantly identity)
                  send-message mock-fn
                  env updated-env
                  some-constant 100]
      (f))))
~~~

One particularly odd thing is that removing the import/with-redefs item for `fn-2` or `fn-3` will change the linting result, causing some of the false warnings to not appear.

This is the linting output I see:

~~~
~/travelboss/gdsboss $ bin/clj-kondo --lint foo.clj 
foo.clj:3:26: warning: #'foo/some-constant is referred but never used
foo.clj:4:14: warning: namespace utils.kafka is required but never used
foo.clj:4:34: warning: #'utils.kafka/send-message is referred but never used
foo.clj:7:1: warning: Unused private var foo/mock-fn
foo.clj:13:9: warning: unused binding updated-env
linting took 32ms, errors: 0, warnings: 5
~~~

**expected behavior**

No linting warnings output for the above file. This was also the behavior in clj-kondo releases before the most recent one.

**Comment by borkdude** [comment]
@thobbs Darn lazy evaluation...

Can you try with this new linux binary? 

https://8016-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2020.01.11-SNAPSHOT-linux-amd64.zip

**Comment by thobbs** [comment]
Wow, thank you for the super fast response!

I just tested the new binary with our full codebase and it looks great. It fixes all of the issues that appear to have been introduced.

Thanks for your hard work, and for creating such a useful tool!

**Comment by borkdude** [comment]
Just released a new version. Thanks for posting the issue.
