### ISSUE TITLE
Create static binary for linux build

### ISSUE THREAD

**Issue by didibus** [borkdude/clj-kondo#703]
I used to run clj-kondo on an old Linux which has an old version of GLIB_C, but it seems that the binary is now dynamically linked, and so it doesn't run anymore. Would it be possible to make a statically linked binary for linux, so it can run even on old systems which don't have the right version of GLIBC ?

```
clj-kondo: /lib64/libc.so.6: version `GLIBC_2.14' not found
```

I think it just needs to be called with the `--static` option when compiled, from the doc here: https://www.graalvm.org/docs/reference-manual/native-image/

**Comment by borkdude** [comment]
@didibus Are you able to find out what previous release still worked by looking at the history of `script/compile` and/or bisecting old release from the Github releases page? The `--static` option may have been removed because of some reason which I don't remember off the top of my head.

**Comment by borkdude** [comment]
Also, feel free to make a fork and test this out on your old version of linux and check if it works with `--static`. Then make a PR. I believe this option doesn't work for every OS, which might be the reason why it was removed.

**Comment by borkdude** [comment]
Another thing to think about: would it not be possible to install glibc 2.14 on the old linux machine?

**Comment by didibus** [comment]
> Are you able to find out what previous release still worked by looking at the history of script/compile and/or bisecting old release from the Github releases page? The --static option may have been removed because of some reason which I don't remember off the top of my head.

I just manually tried older and older versions until I found the first one to work. So last version that worked for me was: `Thu 07 Nov 2019 09:06:19 AM UTC`.

> Also, feel free to make a fork and test this out on your old version of linux and check if it works with --static. Then make a PR. I believe this option doesn't work for every platform (macOS, Windows), which might be the reason why it was removed.

The doc says on Windows and macOS the option has no effect: `Warning: On systems other than Linux, this option has no effect`. I'm not sure what that implies exactly.

I could try, but I'm pretty sure if I build it on my system it would work, even without this option, since it would link against my version of GLIBC. The issue with GLIBC happens when something is linked against a newer version of it and ran on a system that has an older version of it.

> Another thing to think about: would it not be possible to install glibc 2.14 on the old linux machine? It seems like a pretty old version

I explored that, but I haven't been successful. System is running Amazon Linux Bare Metal 2012: https://aws.amazon.com/amazon-linux-ami/2012.03-release-notes/

**Comment by didibus** [comment]
Looking through the history of the compile script, it doesn't seem like `--static` option was ever used. So maybe the build server was upgraded recently? And with it it brought a new version of GLIBC ? Like possibly it used to link against an older GLIBC ?

**Comment by didibus** [comment]
Digging a bit more, it seems that it isn't possible to create true statically linking binaries for Windows and MacOS (without some pretty hacky mechanism). So I suspect that's why `--static` mentions that it does nothing on Windows and MacOS.

**Comment by borkdude** [comment]
On November 22 the GraalVM version was bumped to 19.3.0. It could be that this requires a newer version of glibc. I'll try to get this confirmed in the native-image channel on GraalVM slack.

**Comment by borkdude** [comment]
This is one of the replies from that channel:

> 19.3 links native code from openjdk, before it wasn't like that. I'm sure it can influence glibc somehow

**Comment by borkdude** [comment]
@didibus I've created a static linux build in a branch. This is the artifact link: https://8738-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2020.02.16-SNAPSHOT-linux-amd64.zip. Could you test this on your contrained environment?

**Comment by DavidVujic** [comment]
I just tried the static linux build and think it works fine in Alpine Linux! I think the problem we have (https://github.com/borkdude/clj-kondo/issues/772) is related to this issue.

This is how I have tried it out.

Downloaded the static build from the link in the comment above by @borkdude and extracted it.

Ran `docker build` using this example Dockerfile:
``` 
FROM alpine:3.11

RUN apk add --update --no-cache \
    openjdk8-jre \
    nodejs \
    nodejs-npm \
    make \
    bash \
    curl

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY clj-kondo .
```
![alpine-clj-kondo (1)](https://user-images.githubusercontent.com/301286/75383140-18c78600-58dc-11ea-9e9f-e4a7966479fa.png)

**Comment by borkdude** [comment]
@DavidVujic For [babashka](https://github.com/borkdude/babashka/) there will be a separate linux-static download going forward: https://github.com/borkdude/babashka/releases/tag/v0.0.73
I think I'll do the same for clj-kondo, so people who need this (e.g. for Alpine) can download it. The normal builds will remain dynamically linked (@lispyclouds can explain it better than me why this is preferable).

**Comment by didibus** [comment]
I tried the static binary and it does work!

Thank You
