### ISSUE TITLE
Do not trigger obsolote do warning over #(do :foo :bar)

### ISSUE THREAD

**Issue by thenonameguy** [borkdude/clj-kondo#72]
Even though the `fn` body has an implicit `do` block, the `fn` shorthand `#()` requires us to write out an explicit `do` if we want to do multiple operations in it.

**Comment by borkdude** [comment]
Thanks!

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/83ed5f923630b61697d7711d524388a3a861d85d
