### ISSUE TITLE
Read config file from home directory

### ISSUE THREAD

**Issue by Limess** [borkdude/clj-kondo#736]
**Is your feature request related to a problem? Please describe.**
When adding clj-kondo for my personal use across projects in an organisation which does not use it as their main linting tool I find myself having to duplicate configuration in a number of repositories due to shared dependencies.

**Describe the solution you'd like**
clj-kondo should default to reading configuration from `~/.clj-kondo` if no project configuration is found. This behaviour mirrors behaviour of linters from other ecosystems, for example `eslint`.

**Comment by borkdude** [comment]
@Limess So far I've resisted this because of design principle 5.2 here: https://github.com/borkdude/clj-kondo/blob/master/doc/dev.md#design-principles. 

An easy way to get around this is to either use the `--config` flag that accepts additional configuration or a tiny script that copies your system-wide config and (deep)merges it with your project config, e.g. with [babashka](https://github.com/borkdude/babashka):

```
$ bb '(merge-with merge (edn/read-string (slurp "/tmp/config.edn")) (edn/read-string (slurp "/tmp/config2.edn")))'
{:linters {:type-mismatch {:level :off}, :missing-docstring {:level :warning}}}
```

**Comment by Limess** [comment]
Thanks for taking the time to reply. While I still think this would be useful in some scenarios (perhaps as an option in the language server protocol you maintain https://github.com/borkdude/clj-kondo.lsp for use in Calva, etc) I'll close this as it's been considered.

**Comment by borkdude** [comment]
Maybe this comes in handy: https://github.com/borkdude/clj-kondo-configurator

**Comment by bfontaine** [comment]
@borkdude If I’m not mistaken all these solutions allows you to merge config maps but not hooks.

I’m adding clj-kondo to all my team’s projects, but most of them need the same hooks. It’s not viable to copy/paste them everywhere. I could circumvent the issue by asking everyone to clone a hooks repo somewhere then symlink it in the `.clj-kondo` directory of each one of their project but that’s a bit cumbersome.

**Comment by borkdude** [comment]
I agree that is a bit cumbersome, but currently there isn't a good solution for this yet. See also https://github.com/borkdude/clj-kondo/issues/559#issuecomment-684059251. 

I think currently the best solution is to write a script to download/copy/merge the base config into your projects.
You can either do this via the JVM with clj-kondo as a library or via babashka as a pod: https://github.com/borkdude/clj-kondo#babashka-pod. Clj-kondo has a function called merge-configs in the core API.

**Comment by borkdude** [comment]
One thought I was having recently:

In the .clj-kondo/config.edn file we could add something like `{:extra-config-dirs ["~/dev/configs/.clj-kondo"]}` so clj-kondo would merge the current config with those configs and also look in their .clj-kondo dirs for paths.

**Comment by borkdude** [comment]
Let's discuss in #992 for further ideas.
