### ISSUE TITLE
Install script: add parameter for temporary download directory

### ISSUE THREAD

**Issue by bhougland18** [borkdude/clj-kondo#748]
Can you add a parameter to the install script to allow the user to set an alternate download directory?  I am using the Fedora Silverblue Linux distribution and it will not allow changes to /tmp as it is based on OSTREE and is mostly an immutable os.

However, the distribution does allow for the user to write to usr/local/bin, so the rest of the script is fine (especially since the install directory parameter also exists).

**Comment by borkdude** [comment]
@bhougland18 I welcome a PR that adds a `--download-dir` option.

**Comment by borkdude** [comment]
Seems fixed now. Can you test @bhougland18 ?

**Comment by bhougland18** [comment]
Michiel,

I appreciate your help and will test this evening.  Sorry for the delay, I
no longer use Clear OS on my backup machine so haven't been in need of the
change (I felt bad for not making the pull though).  On a related note, I
just made a fork of Nix packages this evening so I could package babashka
for use on my main Nixos machine.  I may ask you a few questions if my
build fails for any reason.  Your stuff is great, I can't wait to get Jet
in Nix packages as well.


Thanks!
Ben Hougland
