### ISSUE TITLE
`==== Testing` bit can be repeatedly printed

### ISSUE THREAD

**Issue by vemv** [borkdude/clj-kondo#749]
Hi again,

I'm giving a quick shot to hacking on clj-kondo. I use the Reloaded workflow. Fortunately I found the source and tests to play fine with it.

I only found  the following  bit:

```clj
(if (= lint! #'lint-jvm!)
  (println "==== Testing JVM version" (clojure-version))
  (println "==== Testing native version"))
```

...To be a bit annoying because it will be printed on many `(refresh)`es.

Don't know its purpose. Maybe it can be wrapped with `(when (System/getEnv "CI"))` or such?

Thanks - V

**Comment by borkdude** [comment]
This is printed so I will know I'm testing either the native or the JVM version when running `lein test` and I'm not accidentally testing the wrong thing (e.g. I have an old binary around and I made some changes to only the JVM version).

**Comment by vemv** [comment]
👍! With a bit of luck there would be a way to have it printed just once.

**Comment by borkdude** [comment]
@vemv I would be ok with some kind of atom that is set to true after the initial print. PR welcome.

**Comment by borkdude** [comment]
Oh, but if you're using the reloaded workflow, that atom will also be reloaded right? ;-)

**Comment by vemv** [comment]
Reloaded wipes atoms too, so a change that worked might be overly obstrusive.

If there's no simple fix (e.g. move this code somehow to the `lein` run) I'd be OK with the issue being closed
