### ISSUE TITLE
Cannot run command on Alpine Linux

### ISSUE THREAD

**Issue by DavidVujic** [borkdude/clj-kondo#772]
**version**
2020.1.13

**platform**
Alpine Linux
**editor**
n/a
**problem**
I think the problem is because of a prebuilt binary included in the clj-kondo npm package cannot be run in Alpine Linux. Perhaps it has to do with `libc` vs `musl`?

reference: https://github.com/elm-explorations/test/issues/31

Shortened error output from the CI build:
``` 
...node_modules/clj-kondo/unpacked_bin/clj-kondo ENOENT
....
  spawnargs: [ '--lint', 'src' ] ...
```
**repro**
run `npx clj-kondo --version` or `--lint <my-folder>`.

**expected behavior**

[ What is the behavior you expected to see from clj-kondo? ]

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

**Comment by borkdude** [comment]
@DavidVujic Can you test with the static linux build? 

https://github.com/borkdude/clj-kondo/issues/703#issuecomment-590059831

**Comment by DavidVujic** [comment]
Ok! I'll give it a try!
