### ISSUE TITLE
Cursive setup screenshot shows different scope to instructions

### ISSUE THREAD

**Issue by timothypratley** [borkdude/clj-kondo#774]
Thanks for a great too and clear setup instructions.
There is one small inconsistency in [Cursive Setup](https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md#file-watchers--installed-binary)
where the screenshot shows "Scope: All Places", but instructions say "Scope: Current file".

Also when selecting "File type" there is a CLJX option, I wonder if that can be used to set up one single watcher instead of CLJ CLJC CLJS separately.

**Comment by borkdude** [comment]
Hi @timothypratley,

Feel free to provide a new (preferably high res/Retina) screenshots and instructions. As I'm not using IntelliJ myself on a daily basis I'm open to be corrected by someone who is :).
