### ISSUE TITLE
Document setting up clj-kondo with Clojure-Kit on IntelliJ

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#786]
See https://github.com/gregsh/Clojure-Kit/
PR welcome at doc/editor-integration.md.

**Comment by timothypratley** [comment]
Hi @borkdude 

Clojure-Kit appears to be in the same space as Cursive; plugins for Clojure.
For reference, I do use Cursive, but not Clojure-Kit.
Neither of them requires specialized instructions.
The `clj-kondo` integration is orthogonal and works independently of them.

FWIW I recommend closing this issue as not required.
If I'm missing the point though, let me know, as I'm happy to help here.

**Comment by borkdude** [comment]
@timothypratley 

The point of the person bringing it to my attention was that with Clojure-Kit you can achieve something similar as with FileWatchers but you do not need to have Cursive installed.

The FileWatchers config needs to see some file types and these file types are defined by Cursive. I.e. when you do not use Cursive, you cannot use FileWatchers because there are no file types to choose from.

With Clojure-Kit you would only have to define one type of command line action for one type of Clojure file and then it would work for all Clojure files in all projects.

One downside of FileWatchers is that it only works in commercial versions of IntelliJ. Clojure-Kit works also in the community edition.

**Comment by timothypratley** [comment]
Oh - I see, thank you for the clarification.
I am using the Community Edition and was able to install FileWatchers just fine.
Even though the "FileWatchers" plugin is bundled with the commercial version, you don't need the commercial version to install it.
I can update the instructions to call this out.

**Comment by borkdude** [comment]
Seems like a good idea!
