### ISSUE TITLE
Handle core.logic 

### ISSUE THREAD

**Issue by interstar** [borkdude/clj-kondo#799]
A couple of quirks when using with core.logic 

Defining a db-relation with

```
(pldb/db-rel link from to)
```

produces 

```
src/clj_ts/logic.clj:10:14: error: unresolved symbol link
src/clj_ts/logic.clj:10:19: error: unresolved symbol from
src/clj_ts/logic.clj:10:24: error: unresolved symbol to
```

While defining logic variables inside a 

```
(run* [p q] ... )
```

also gives

```
src/clj_ts/logic.clj:11:19: error: unresolved symbol p
```

**Comment by borkdude** [comment]
Have you looked at

- https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#exclude-unresolved-symbols-from-being-reported 
- https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#lint-a-custom-macro-like-a-built-in-macro ?

**Comment by interstar** [comment]
Ah. That looks useful. But where does that {:linters go?

is it inside the map called :clj-kondo in my :aliases map? Or is it another subling of that :clj-kondo map?

**Comment by borkdude** [comment]
@interstar Please read this: https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#configuration.

**Comment by interstar** [comment]
Thanks
