### ISSUE TITLE
support clojure.java.jdbc/with-transaction macro

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#821]
From Slack:

Both clojure.java.jdbc and next.jdbc have a "with transaction" style macro that has the form (with-transaction [sym expr opts] & body) -- sym is introduced by the macro, for the body (like binding or several other core macros) but if I tell kondo to :lint-as any of those macros, it then complains about opts since a binding form should be an even number of forms. Can anyone think of a core macro that has an optional extra expression in a binding like that?

**Comment by seancorfield** [comment]
Resolved by #823
