### ISSUE TITLE
Add `:exclude` key for `unsorted-required-namespaces`

### ISSUE THREAD

**Issue by Heliosmaster** [borkdude/clj-kondo#844]
I'd like to add an `:exclude` option to the `unsorted-required-namespace` that works similarly as `:exclude` key in other linters. I.e. you add a string and the linter is not run if the namespaces matches one or more of the eclusions.

If you're okay with it, I'll do the PR :)

**Comment by borkdude** [comment]
Can you make the problem statement? In which situation does this solve a problem?

**Comment by Heliosmaster** [comment]
Sure: 

- at Nextjournal we have quite a bit of unsorted namespaces that we would like to fix, but they are so many that it won't happen all at once. 
- We also depend on clj-kondo for our CI and right now this linter is disabled.

I would like to slowly enable it for all namespaces, as we clean it up.

**Comment by borkdude** [comment]
@Heliosmaster Can you be more specific and give some examples?

**Comment by Heliosmaster** [comment]
I don't mean adding metadata to the namespace itself, but on the configuration of the linter.

We already have

```
 :unused-namespace {:level :warning
                                 :exclude [clj-kondo.impl.var-info-gen]
                                 }
```

I'd like to have the same for the other linter, something as:

```
  :unsorted-required-namespaces {:level :warning
                                                           :exclude ["foo.bar"]
                                                           }
```

The linter, when parsing a ns form, will look whether "foo.bar" is a substring of the ns. If so, will skip the linting in that particular ns.

**Comment by borkdude** [comment]
I think that configuration can appear quite ambiguous, since it could also mean to suppress the warning when that namespaces is required. This is how that configuration is used in most cases: not to exclude warnings inside that namespace, but warnings about that namespace.

The way to turn off warnings for a specific linter inside a namespace can be done using metadata on the namespace:

```
(ns foo {:clj-kondo/config {:linters {:unsorted-required-namespaces {:level :off}}}}
    (:require [clojure.string]
              [clojure.set]))
```

**Comment by Heliosmaster** [comment]
I understand what you say about the `:exclude`. I was probably more inspired by the `{:outputs :exclude-files {}}` part of the configuration. 

However, I think this issues touches a more general concept about clj-kondo: how do you think large existing codebase can be _made_ compliant to clj-kondo? Right now there is an all-or-nothing, for either a linter or a file. What is your opinion?

**Comment by borkdude** [comment]
My opinion is that you can use a diff file (check out `script/diff`) and then process that diff to check if there are additional errors. Tools like reviewdog are tailored to this use: https://github.com/reviewdog/reviewdog. We can document Reviewdog somewhere.

**Comment by borkdude** [comment]
I have asked someone who uses clj-kondo with reviewdog to share his config.

Another option is to use a pre-commit hook: https://github.com/borkdude/clj-kondo/issues/835 to lint touched files. If they give any warnings/errors the commit is cancelled.

**Comment by borkdude** [comment]
@Heliosmaster Here's a zip with config.edn (clj-kondo), config.yml (CircleCI) and a lint bash script which they use for linting diffs using ReviewDog.
[juxt-lint-config.zip](https://github.com/borkdude/clj-kondo/files/4438935/juxt-lint-config.zip)

**Comment by Heliosmaster** [comment]
Thanks! However, we don't use any external CI service such as CircleCI but we dogfood our own infrastructure, but I am essentially building a notebook to achieve the same :)

**Comment by borkdude** [comment]
@Heliosmaster Cool. If you have anything useful to document in that area, I'd love to see it.
