### ISSUE TITLE
Emit warning for all usages of `:refer`

### ISSUE THREAD

**Issue by esuomi** [borkdude/clj-kondo#847]
**Is your feature request related to a problem? Please describe.**
Within my peers we have an in-house guidance which strongly discourages the use of `:refer` and `:refer-macros` within namespace `requires` to make the code more legible by clearly highlighting where the function/macro is defined. That is, instead of
```clojure
(ns my.cool.ns
  (:require [awesome.bits :refer :all]
            [important.stuff :refer [this where?]])

(-> where-did-this-come-from
    this
    belongs
    where?)
```
we enjoy this form more:
```clojure
(ns my.cool.ns
  (:require [awesome.bits :as awe]
            [important.stuff :as stuff])

(-> awe/where-did-this-come-from
    important/this
    awe/belongs
    important/where?)
```
**Describe the solution you'd like**
As suggested by @borkdude himself on Slack, something similar to `:use {:level :warning}` for enforcing this would be great. Considering options I see the following possible configurations for this:
 1. for each use of `:refer`
   - ...emit warning for `:refer [<symbols>]`
   - ...emit warning for `:refer :all`
   - ...always emit a warning
 1. emit warning for each use of `:refer-macros` _(for CLJC/CLJS)_
 1. emit warning for each use of `:include-macros` _(for CLJC/CLJS)_

**Describe alternatives you've considered**
I did consider building something on top of [analysis data](https://github.com/borkdude/clj-kondo/tree/master/analysis) provided by clj-kondo but quickly decided against that in favor of having something more native, besides the personal general lack of time and unfamiliarity of kondo's internal workings.

**Comment by borkdude** [comment]
Hmm, maybe `:use` + `:only` doesn't make sense. Thoughts?
