### ISSUE TITLE
Add support for slingshot

### ISSUE THREAD

**Issue by pablo-develop** [borkdude/clj-kondo#874]
[slingshot](https://github.com/scgilardi/slingshot) is a popular library and to silence clj-kondo errors its necessary to ignore the whole `try+` block, when the problem relies on the catch clause format
```clojure
(catch [:type :my-error] {:keys [msg <-- error here]}
  ...)
```

**Comment by borkdude** [comment]
Slingshot is support in the config library here: https://github.com/clj-kondo/config
