### ISSUE TITLE
Support string requires at top on :unsorted-required-namespaces

### ISSUE THREAD

**Issue by wilkerlucio** [borkdude/clj-kondo#885]
**Is your feature request related to a problem? Please describe.**

Tools like https://github.com/immoh/lein-nsorg can sort all requires automatically, but since they use pure alphabetical order, string requires are placed on the top of the list. This is also a pattern that I follow and I see in other codebases, having the string requires at top. 

Currently, the unsorted-required-namespaces considers only the namespace name (like if all of them are symbols, or strings, no distinction).

**Describe the solution you'd like**
I like to have a configuration option so that I can tell clj-kondo to consider the requires order taking the string vs symbol into account, so strings are validated at the top.

Example of the change:

```clojure
; this is what I consider organized
(ns devcards.render
  (:require
    ["react" :as react]
    [devcards.util :as d-u]
    [reagent.core :as r]
    [relemma.util :as u]))
; this is what clj-kondo considers organized
(ns devcards.render
  (:require
    [devcards.util :as d-u]
    ["react" :as react]
    [reagent.core :as r]
    [relemma.util :as u]))
```

To do that, we could have a flag on `:unsorted-required-namespaces` to let clj-kondo know which way is preferred (so it won't break for existing users).

```clojure
:unsorted-required-namespaces {:level :warning :strings-first? true}
```

**Describe alternatives you've considered**

An alternative is to use multiple `:require` entries to separate strings and symbols:

```clojure
(ns devcards.render
  (:require
    ["react" :as react])
  (:require
    [devcards.util :as d-u]
    [reagent.core :as r]
    [relemma.util :as u]))
```

**Additional context**

I can work on the PR myself in case we consider this to be a desired feature.

**Comment by borkdude** [comment]
@wilkerlucio Can you check if all or most codebases use this convention and if all or most of the namespace sorting tooling put strings on top? If so, then this probably should become the default in clj-kondo as well.

Maybe this is also something to discuss with https://github.com/bbatsov/clojure-style. Note that I also made an issue there for reader conditionals (which are expected to put first in sorting now in clj-kondo): https://github.com/bbatsov/clojure-style-guide/issues/205

**Comment by borkdude** [comment]
It seems `clojure-mode` puts string requires on top. As this is the most widely used Clojure way of sorting, I'm proposing that clj-kondo also sticks to this and that we make this the default without an additional option.

**Comment by borkdude** [comment]
Fixed on master.
