### ISSUE TITLE
Suggest zero?, pos? and neg? 

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#91]
`(= 0 x)` => `(zero? x)`, etc.

**Comment by marcomorain** [comment]
This is not a safe transformation – I once broke production with one of these refactors. I had a function that would execute a program, and return a map with keys `out`, `err`, `exit`. It turned out that in some cases, `exit` was nil, instead of an integer.

```
user=> (zero? nil)
Execution error (NullPointerException) at user/eval1 (REPL:1).
null
user=> (= 0 nil)
false
```

**Comment by borkdude** [comment]
Thanks!
