### ISSUE TITLE
Add `:base-lang` and `:lang` to hook API

### ISSUE THREAD

**Issue by rschmukler** [borkdude/clj-kondo#920]
**Is your feature request related to a problem? Please describe.**
Some macros can compile differently as `cljs` or `clj`. The hooks API currently has no way to distinguish which version of the macro is being invoked, making it impossible to account for these types of macros.

**Describe the solution you'd like**
Per the Slack, it would be helpful if the context keys used internally by clj-kondo for this (`:base-lang` and `:lang`) could also be passed into the hook API.

**Describe alternatives you've considered**
I have not considered any alternatives as this was the recommendation of @borkdude per the `#clj-kondo` channel in the Clojurians Slack.

**Comment by borkdude** [comment]
Related: #811

**Comment by borkdude** [comment]
@rschmukler Added the following keys:

- `:cljc`: `true`, `false` 
- `:lang:`: `:clj` or `:cljs`
- `:filename`: the name of the file currently linted
