### ISSUE TITLE
It would be great ability to use hooks already defined in clj-kondo/libraries directly

### ISSUE THREAD

**Issue by abogoyavlensky** [borkdude/clj-kondo#923]
**Is your feature request related to a problem? Please describe.**
For now as I understand the only way to use predefined (in clj-kondo/libraries source) hooks is copy hook file into project dir, for example: `.clj-kondo/hooks/slingshot/try_plus.clj`. If I have several project I should copy it every time for every unusual macro. It is slightly not convenient and might be tedious.

**Describe the solution you'd like**
It would be great if I could point in `.clj-kondo/config.edn` already predefined hook in clj-kondo itself without need to copy entire hook every time.

**Describe alternatives you've considered**
As an alternative probably there is ability to point hook from any other project's required lib. In other words: any way to share hooks between project would be nice.

**Additional context**
Probably I missed something from the doc and maybe something similar is already available to use, probably here:

> If the hooks use common code, you can put that in a library namespace and use require to load it from each hook's namespace.

But I didn't get the idea a bit. Thanks!

**Comment by borkdude** [comment]
Related #559

**Comment by borkdude** [comment]
Check out https://github.com/clj-kondo/config
