### ISSUE TITLE
Cannot configure `unused-private-var` linter via ns meta

### ISSUE THREAD

**Issue by serioga** [borkdude/clj-kondo#924]
Similar to issue with `:unused-import`.

_Originally posted by @serioga in https://github.com/borkdude/clj-kondo/issues/909#issuecomment-648697938_

**Comment by borkdude** [comment]
Discovered a bug with ns-local config: overriding  config for a linter would erase other settings for that linter instead of being merged in. Need to write a test for this + for the actual issue reported here. Work in progress in the `issue-924` branch.
