### ISSUE TITLE
Support building on JDK-11 based GraalVMs

### ISSUE THREAD

**Issue by rschmukler** [borkdude/clj-kondo#925]
**version**

`clj-kondo v2020.06.22-SNAPSHOT` - built with 4669301

**platform**

Building native with GraalVM 20.1.0, using OpenJDK 11.0.7

**problem**

Currently the build fails due to the reflection issues that are solved with https://github.com/borkdude/clj-reflector-graal-java11-fix

Adding that as a dependency to the `:clojure-1.10.2-alpha1` lein profile did not 

**repro**

Run `./script/compile` with `$GRAALVM_HOME` set to a graal install with the appropriate version.

**expected behavior**

The project to build successfully.

**Comment by borkdude** [comment]
Done.
