### ISSUE TITLE
Investigate performance of memoized config

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#928]
From https://www.reddit.com/r/Clojure/comments/hgxgax/blogpost_how_i_sped_up_datahikes_datalog_parser/fw74r3s?utm_source=share&utm_medium=web2x

> Looks like ~40% of CPU time is spent accessing memoized values due to Clojure's equality semantics. looking at clj-kondo.impl.config. If you could find a way to cache these results without using memoize you'll speed things up. It might also be a function of the number of files linted. I profiled the kondo on its own code base.

**Comment by bsless** [comment]
github doesn't support uploading svg files, so here's a mega link
https://mega.nz/file/6IsRybxL#qzFxV6moNZnHzeLDzKZRHRH3nMMTf-pyUPxnpTX8tYc
take a look at `lint-var-usage` in particular

**Comment by borkdude** [comment]
@bsless Github does support uploading .zip files, so zipping it would also be a good solution. I'm not seeing the same as you do. I made it a little bit easier to profile using clj-async-profiler now on master:

https://github.com/borkdude/clj-kondo/blob/master/doc/dev.md#profiling

Can you post the command you used to make your flamegraph, so I can reproduce it locally?

**Comment by bsless** [comment]
Ah, I did something a bit different.
```clojure
(def opts {:lint ["./"]})
(require '[clj-async-profiler.core :as prof])
(prof/profile
 (dotimes [_ 40]
   (clj-kondo/run! opts)))
(prof/serve-files 7777)
```

**Comment by borkdude** [comment]
@bsless There may be laziness involved. So try with `(clj-kondo/print! (clj-kondo/run! opts))`.

**Comment by bsless** [comment]
ack, bitten again by laziness! will try

**Comment by bsless** [comment]
note: I also tested in the JVM and not as a native image

**Comment by borkdude** [comment]
Yes, same here.

**Comment by bsless** [comment]
[02-cpu-flamegraph-2020-06-28-13-15-27.svg.zip](https://github.com/borkdude/clj-kondo/files/4842061/02-cpu-flamegraph-2020-06-28-13-15-27.svg.zip)
Still getting similar results.
What I don't understand is the `frame_buffer_overflow` section. According to clj-async-profiler it could be an OS bug on my end: https://github.com/jvm-profiling-tools/async-profiler#troubleshooting
Need to see what I can do about that

**Comment by borkdude** [comment]
@bsless I suggest making an SVG using `clojure -A:profile --lint src test` (or linting other files) as this gives a more realistic picture of what's normally going on inside clj-kondo. If there's anything coming out of that I'd be happy to address it. Or if you can reproduce the memoize behavior using this command, that'd be good too, then we'd have something reproducible to talk about.
