### ISSUE TITLE
Documentation explaining the different mistakes/style issues detected

### ISSUE THREAD

**Issue by Tiv0w** [borkdude/clj-kondo#936]
## Problem

Hello, I'm a super beginner with Clojure, and using `clj-kondo` I'm sometimes not helped at all. I make mistakes in my code (which is normal as a beginner), `clj-kondo` tells me about these errors, but I absolutely don't know what to do with an information like:
> file.clj:36:5: warning: inline def

I'm willing to refactor it to something better, but I don't know what to refactor it to!
I also don't know if it's a logic issue or a style issue.
  

## Solution

At least a simple Markdown or text file to list and document the potential errors/warnings thrown by `clj-kondo`, and indications on how to refactor them (in my above example: change inline def to a `let` binding).

## Alternatives

Rust tooling provides with the linter a `--explain [ERROR CODE]` command, which prints a small explanation of the error, and most of the times how to remedy to the given error. 

---
I could try to collect and gather information and documentation about the errors as I learn and then open a PR, but I think we're all better off with the documentation of someone who actually knows Clojure and why those errors are being reported. (Not me :innocent: )

**Comment by borkdude** [comment]
Thanks! I think that would certainly be good to add. I've also been meaning to add a full list of all possible linters for the configuration page (https://github.com/borkdude/clj-kondo/blob/macros-sci/doc/config.md).

As for `inline def`, this means that you are using `def` within a `def` or `defn`. This isn't idiomatic Clojure. For the inner `def` you should probably use `let`. More about the explanation of the term `inline def` here:

https://blog.michielborkent.nl/2017/05/25/inline-def-debugging/

**Comment by Tiv0w** [comment]
Adding a list of the linters would really help newcomers as well!
I really appreciate that you're open to suggestions, and in particular to help newbies like me.

And yeah, after some Googling, and some docs reading, I found out why the `inline def` error and corrected it in my code.

Anyway, thanks for `clj-kondo` and helping a beginner like me start with some notions of idiomatic Clojure! :tada:

**Comment by borkdude** [comment]
@Tiv0w The list is now available here: https://github.com/borkdude/clj-kondo/blob/master/doc/linters.md.
Let me know what you think.

**Comment by vemv** [comment]
Looks great to me!

It will help me upgrade a project which was using an old clj-kondo dep.

(I assume the list is exhaustive)

**Comment by borkdude** [comment]
@vemv Yes, the list is (or should be) exhaustive.
