### ISSUE TITLE
Detect duplicate keys in map literals

### ISSUE THREAD

**Issue by nwjsmith** [borkdude/clj-kondo#94]
```clojure
{:duplicated "once" :duplicated "twice"}
```
Should result in an error

**Comment by borkdude** [comment]
Note that this feature is already supported by [joker](https://github.com/candid82/joker), so meanwhile you might want to turn that one on as well.

**Comment by borkdude** [comment]
@nwjsmith How does this look?
<img width="320" alt="Screenshot 2019-04-22 10 59 17" src="https://user-images.githubusercontent.com/284934/56493040-062b3600-64ee-11e9-95bc-50ec87912827.png">

**Comment by borkdude** [comment]
Fixed with 9f9901c818325912d0da1de10c18a2cd17a2acee

**Comment by nwjsmith** [comment]
@borkdude Thank you!
