### ISSUE TITLE
Detect odd number forms in map literal

### ISSUE THREAD

**Issue by nwjsmith** [borkdude/clj-kondo#95]
```clojure
{1}
```
Should result in an error

**Comment by borkdude** [comment]
Note that this feature is already supported by [joker](https://github.com/candid82/joker), so meanwhile you might want to turn that one on as well.

**Comment by borkdude** [comment]
How about this?

<img width="348" alt="Screenshot 2019-04-22 11 00 22" src="https://user-images.githubusercontent.com/284934/56493070-1e02ba00-64ee-11e9-8b77-c9a3c22c2241.png">

**Comment by borkdude** [comment]
Fixed with 9f9901c818325912d0da1de10c18a2cd17a2acee

**Comment by nwjsmith** [comment]
@borkdude thanks!

**Comment by borkdude** [comment]
@nwjsmith I'd like to keep the issue open until it's properly released, that's why I reopened it. It will be closed once published.
