### ISSUE TITLE
Wiki section with user contributed analyze-call hooks?

### ISSUE THREAD

**Issue by andreyorst** [borkdude/clj-kondo#998]
What's you opinion on creating a section in Wiki where clj-kondo users could share and improve custom linters we create to lint our code, that is not directly supported by clj-kondo?

Currently many feature requests ask to add support for a certain popular library, but I think many who don't really want to wait for official support define their own `lint-as` and `analyze-call` directives. This feels like in Clojure spirit itself - we can expand the linter as we expand language with macros, we just need a place to share ideas, and I think GitHub Wiki is a decent one.

Or maybe there's already such place that I'm just unaware of?

Thanks!

**Comment by borkdude** [comment]
@andreyorst I'm working on a feature in clj-kondo that lets you pull in config from other places (#992). If you have library specific hooks, you can contribute them to https://github.com/clj-kondo/clj-kondo.configs so other users can pull that in.

**Comment by andreyorst** [comment]
Understood. Thanks!

**Comment by borkdude** [comment]
@andreyorst The other place would be the `examples` directory in this repo, which is just what is is, examples. But most of that is now copied to the config lib.

**Comment by andreyorst** [comment]
I've chosen the contribution approach :)
